// 4K影视 public guest adapter. No browser, account rotation or remote JS execution.
var Vm4Sites=['https://www.4kvms.org','https://www.4kvms.com','https://www.4kvm.top','https://www.4kvm.org','https://www.4kvm.tv'];
var Vm4Categories=[['0','全部'],['1','电影'],['2','电视剧'],['3','动漫'],['4','综艺']];
function vm4SiteParam(){return {name:'site',title:'网站入口',type:'enumeration',value:Vm4Sites[0],enumOptions:Vm4Sites.map(function(s){return {title:s.replace('https://',''),value:s};})};}
function vm4ListParams(){return [vm4SiteParam(),{name:'category',title:'分类',type:'enumeration',value:'0',enumOptions:Vm4Categories.map(function(c){return {value:c[0],title:c[1]};})},{name:'sort',title:'排序',type:'enumeration',value:'update_time',enumOptions:[{title:'原站近期更新',value:'update_time'},{title:'热门',value:'hits'},{title:'评分',value:'score'}]},{name:'page',title:'页码',type:'page',value:'1'}];}
var WidgetMetadata={id:'joeshu.4kvm',title:'4K影视',author:'joeshu',site:Vm4Sites[0],version:'0.1.0',requiredVersion:'0.0.1',description:'独立片库、搜索、完整分集与游客可用画质；4K会员资源以原站权限为准。',detailCacheDuration:0,
 modules:[{id:'home',title:'首页推荐与更新',functionName:'loadHome',cacheDuration:60,params:[vm4SiteParam()]},{id:'catalog',title:'分类片库与近期更新',functionName:'loadCatalog',cacheDuration:60,params:vm4ListParams()},{id:'searchList',title:'搜索影片',functionName:'search',cacheDuration:0,params:[vm4SiteParam(),{name:'keyword',title:'片名',type:'input',description:'原站搜索最多返回20条，请使用完整片名'}]},{id:'loadResource',title:'获取游客播放线路',type:'stream',functionName:'loadResource',cacheDuration:0,params:[{name:'qualityPreference',title:'画质优先级',type:'enumeration',value:'highest',enumOptions:[{title:'最高可用画质（自适应）',value:'highest'},{title:'清晰优先（固定高画质）',value:'fixed'}]}]}],
 search:{title:'4K影视搜索',functionName:'search',params:[vm4SiteParam(),{name:'keyword',title:'片名',type:'input',description:'原站搜索最多返回20条，请使用完整片名'}]}};
var VM4={maxBody:4*1024*1024,wasmPath:'/static/wasm/nbmovie_wasm_bg.d5d51939.wasm'},vm4Flights=Object.create(null);
function vm4Text(v){return String(v==null?'':v).replace(/<[^>]*>/g,'').replace(/\s+/g,' ').trim();}
function vm4Site(v){v=v||Vm4Sites[0];if(Vm4Sites.indexOf(v)<0)throw new Error('4K影视网站入口无效');return v;}
function vm4Page(v){var n=Number(v||1);if(!Number.isSafeInteger(n)||n<1||n>1000)throw new Error('页码无效');return n;}
function vm4Parse(link){var m=String(link).match(/^(https:\/\/[^/]+)(\/play\/([A-Za-z0-9_-]{1,80}))$/);if(!m)throw new Error('请选择4K影视模块内的影片或分集');return {site:vm4Site(m[1]),path:m[2],key:m[3]};}
function vm4Path(v){if(!/^\/play\/[A-Za-z0-9_-]{1,80}$/.test(String(v)))throw new Error('4K影视分集地址异常');return v;}
function vm4Url(u){if(typeof u!=='string'||u.length>8192||/[\s\x00-\x1f\\]/.test(u)||!/^https?:\/\/[^/@?#]+(?:[/?#]|$)/i.test(u))throw new Error('4K影视返回了无效资源地址');return u;}
function vm4Headers(site,path){return {'User-Agent':'Mozilla/5.0',Accept:'text/html,application/json',Referer:site+(path||'/')};}
async function vm4Get(site,path,json){vm4Site(site);if(typeof path!=='string'||path[0]!=='/'||/^\/\//.test(path)||/[\r\n\\]/.test(path))throw new Error('4K影视请求路径异常');var r=await Widget.http.get(site+path,{headers:vm4Headers(site,path)}),status=Number(r.statusCode||r.status);
 if(status===429){var e=new Error('4K影视请求过于频繁，请稍后重试');e.code='RATE_LIMIT';throw e;}
 if(status!==200)throw new Error('4K影视入口暂不可用（HTTP '+status+'），请换入口或稍后重试');var data=r.data;
 if(typeof data==='string'&&data.length>VM4.maxBody)throw new Error('4K影视页面过大');
 if(json){if(typeof data==='string'){try{data=JSON.parse(data);}catch(e){throw new Error('4K影视播放接口格式已变化');}}if(!data||Number(data.code)!==200||!data.data)throw new Error('4K影视未返回可用播放资源，请刷新或到原站确认权限');return data.data;}
 if(typeof data!=='string'||!/<!doctype|<html/i.test(data)||/<title>\s*(?:Site Unavailable|访问验证)/i.test(data))throw new Error('4K影视未返回影片页面，请换入口或在原站完成验证');return data;
}
async function vm4Cards(html,site,category){var $=await Widget.html.load(html),seen=Object.create(null),items=[];
 $('a[data-vod][href^="/play/"]').each(function(i,el){var a=$(el),path=a.attr('href');vm4Path(path);if(seen[path])return;var image=a.find('img').first(),title=vm4Text(image.attr('alt')||a.find('h3').text());if(!title)return;seen[path]=true;var cover=image.attr('data-src')||image.attr('src')||'';if(cover&&/^https?:\/\//i.test(cover))cover=vm4Url(cover);else cover='';var box=a.closest('.movie-card'),text=vm4Text(a.text()),year=vm4Text(a.find('span,div').filter(function(i,e){return /^(?:19|20)\d{2}$/.test(vm4Text($(e).text()));}).first().text())||((text.match(/(?:^|\s)((?:19|20)\d{2})(?:\s|$)/)||[])[1]||''),rating=vm4Text(box.find('span').filter(function(i,e){return /^\d\.\d$/.test(vm4Text($(e).text()));}).first().text());var cat=Vm4Categories.find(function(c){return c[0]===String(category);}),link=site+path;
 items.push({id:link,type:'url',link:link,title:title,coverUrl:cover,posterPath:cover,releaseDate:year,rating:rating,mediaType:String(category)==='1'?'movie':'tv',genreTitle:cat&&cat[0]!=='0'?cat[1]:'',description:vm4Text(a.find('p').first().text())||vm4Text(a.find('span').last().text())});
 });return items;
}
async function loadHome(params){var site=vm4Site((params||{}).site);return vm4Cards(await vm4Get(site,'/'),site);}
async function loadCatalog(params){params=params||{};var site=vm4Site(params.site),category=String(params.category||'0'),sort=params.sort||'update_time',page=vm4Page(params.page);if(!Vm4Categories.some(function(c){return c[0]===category;})||['update_time','hits','score'].indexOf(sort)<0)throw new Error('分类或排序无效');var path='/filter?'+(category==='0'?'':'classify='+category+'&')+'sort_by='+sort+'&order=desc&page='+page;return vm4Cards(await vm4Get(site,path),site,category);}
async function search(params){params=params||{};var site=vm4Site(params.site),q=vm4Text(params.keyword).replace(/[\u200b-\u200d\ufeff]/g,'').trim(),page=vm4Page(params.page);if(!q)return [];if(q.length>60)throw new Error('关键词最多60个字符');if(page>1)return [];return vm4Cards(await vm4Get(site,'/search?q='+encodeURIComponent(q)),site);}
async function vm4DecodePage(html,ids){var $=await Widget.html.load(html),manager=$('[x-data]').filter(function(i,el){return /^episodeManager\(/.test($(el).attr('x-data')||'');}).first().attr('x-data');if(!manager)throw new Error('4K影视未提供完整分集，请刷新或更新模块');var declarations=[],re=/\{\s*lineName:\s*'([^'\\]{1,80})'\s*,\s*episodeCount:\s*(\d+)\s*\}/g,m;
 while((m=re.exec(manager)))declarations.push({name:m[1],count:Number(m[2])});if(!declarations.length||declarations.length>20)throw new Error('4K影视线路结构已变化');var lines=declarations.map(function(d){if(d.count<1||d.count>10000)throw new Error('4K影视分集数量异常');return {name:d.name,count:d.count,episodes:[],seen:Object.create(null)};}),byPath=Object.create(null);
 $('a[data-line][data-episode][dataid]').each(function(i,el){var a=$(el),line=Number(a.attr('data-line')),ep=Number(a.attr('data-episode')),id=a.attr('dataid'),path=vm4Path(a.attr('href'));if(!Number.isSafeInteger(line)||!lines[line-1]||!Number.isSafeInteger(ep)||ep<1||ep>10000||!/^\d{1,20}$/.test(id||''))throw new Error('4K影视分集标识异常');if(lines[line-1].seen[ep])throw new Error('4K影视分集编号重复');lines[line-1].seen[ep]=true;var label=vm4Text(a.text());if(!label||/^\d+$/.test(label))label='第'+ep+'集';var e={line:line,number:ep,dataid:id,path:path,key:path.slice(6),title:label};if(byPath[path])throw new Error('4K影视分集地址重复');byPath[path]=e;lines[line-1].episodes.push(e);});
 lines.forEach(function(l){if(l.episodes.length!==l.count)throw new Error('4K影视分集不完整，请刷新后重试');l.episodes.sort(function(a,b){return a.number-b.number;});});if(!byPath[ids.path])throw new Error('4K影视详情与所选分集不匹配');var title=vm4Text($('h1').first().text());if(!title)throw new Error('4K影视影片标题缺失');var cover=$('meta[property="og:image"]').attr('content')||'';if(cover)cover=vm4Url(cover);return {site:ids.site,path:ids.path,title:title,cover:cover,description:vm4Text($('meta[name="description"]').attr('content')),lines:lines,current:byPath[ids.path],html:html,$:$};
}
async function vm4Detail(ids){var key=ids.site+ids.path;if(vm4Flights[key])return vm4Flights[key];vm4Flights[key]=(async function(){return vm4DecodePage(await vm4Get(ids.site,ids.path),ids);})();try{return await vm4Flights[key];}finally{delete vm4Flights[key];}}
async function loadDetail(link){var ids=vm4Parse(link),d=await vm4Detail(ids),currentLine=d.lines[d.current.line-1],item={id:link,type:'url',link:link,title:d.title,coverUrl:d.cover,posterPath:d.cover,description:d.description+'\n当前线路 '+currentLine.name+' · '+currentLine.count+' 个分集条目',mediaType:currentLine.count>1?'tv':'movie'};
 item.episodeItems=currentLine.episodes.map(function(e){var path=d.site+e.path;var item={id:path,type:'url',link:path,title:e.title,coverUrl:d.cover,mediaType:currentLine.count>1?'tv':'movie'};var alternatives=d.lines.map(function(l){return l.episodes.find(function(x){return x.number===e.number;});}).filter(Boolean);if(alternatives.length>1)item.childItems=alternatives.map(function(a){var url=d.site+a.path;return {id:url,type:'url',link:url,title:d.lines[a.line-1].name+' · '+a.title,coverUrl:d.cover};});return item;});return item;
}
function vm4GuestRequest(d){var $=d.$,cfg=$('#wasm-cfg').attr('data-bg');if(cfg!==VM4.wasmPath)throw new Error('4K影视播放器已更新，请更新模块');var st=$('#nb-st').attr('content'),pageToken=$('[x-data]').map(function(i,el){return $(el).attr('x-data')||'';}).get().join('\n').match(/(?:^|[,\s{])userlink:'([A-Za-z0-9_+\/=-]{1,512})'/);if(!/^\d{10,16}$/.test(st||'')||!pageToken)throw new Error('4K影视游客参数缺失，请刷新或到原站确认访问状态');var now=Date.now(),f=vm4Build({st:st,plt:String(now)},now),path=f(d.current.dataid,d.current.key,'1080',pageToken[1]);if(!/^\/video\/play\?p=[A-Za-z0-9_%=-]{1,2048}(?:&(?:v|q|s|t|k)=[A-Za-z0-9_%=-]{0,2048}){5}$/.test(path))throw new Error('4K影视播放请求格式异常');return path;}
function vm4Allowed(q){function openFlag(v){return v===false||v===0||v==='0'||v==='false';}return q&&openFlag(q.locked)&&openFlag(q.isvip)&&typeof q.url==='string'&&q.url.length>0;}
async function loadResource(params){params=typeof params==='string'?{link:params}:params||{};var preference=params.qualityPreference||'highest';if(['highest','fixed'].indexOf(preference)<0)throw new Error('画质选项无效');var ids=vm4Parse(params.link),d=await vm4Detail(ids),data=await vm4Get(ids.site,vm4GuestRequest(d),true);if(!Array.isArray(data.quality_urls))throw new Error('4K影视画质列表已变化');var qualities=data.quality_urls.filter(vm4Allowed);if(!qualities.length)throw new Error('此分集没有游客可用线路，请到原站确认权限或选择其他影片');qualities.sort(function(a,b){return Number(b.bitrate||0)-Number(a.bitrate||0);});var headers={'User-Agent':'Mozilla/5.0'},results=[];
 for(var i=0;i<Math.min(qualities.length,3);i++){var q=qualities[i],url=vm4Url(q.url),info={url:url};if(q.mtype==='m3u8'||/\.m3u8(?:[?#]|$)/i.test(url))info=await vm4Hls(url,headers,preference);else if(q.mtype!=='mp4'&&!/\.mp4(?:[?#]|$)/i.test(url))throw new Error('此资源需要网页播放器，请到原站播放');var name=d.lines[d.current.line-1].name+' · '+vm4Text(q.title||'游客可用画质')+' · '+d.current.title;if(info.width&&info.height)name+=' · 清单 '+info.width+'×'+info.height;if(info.fixed)name+=' · 固定';results.push({name:name,description:'4K影视 · 原站画质标签；实际分辨率以视频为准',url:info.url,playerType:'app',customHeaders:headers});}
 return results;
}
