// Auete public pages. No remote script execution or automatic CAPTCHA solving.
var AuSites=['https://www.au1080.top','https://www.aeete.com','https://www.auete.com'];
var AuCategories=[['Movie','电影'],['Tv','电视剧'],['Dm','动漫'],['Zy','综艺'],['qita','其他']];
function auSiteParam(){return {name:'site',title:'网站入口',type:'enumeration',value:AuSites[0],enumOptions:AuSites.map(function(s){return {title:s.slice(8),value:s};})};}
function auQualityParam(){return {name:'qualityPreference',title:'画质优先级',type:'enumeration',value:'highest',enumOptions:[{title:'最高可用（自适应）',value:'highest'},{title:'固定高画质',value:'fixed'}]};}
var WidgetMetadata={id:'joeshu.auete',title:'Auete影视',author:'joeshu',site:AuSites[0],version:'0.1.0',requiredVersion:'0.0.1',description:'独立分类、近期更新、完整分集与多线路；搜索遇到原站验证码时明确提示。',detailCacheDuration:0,
 modules:[{id:'home',title:'首页推荐',functionName:'loadHome',cacheDuration:60,params:[auSiteParam()]},{id:'latest',title:'连载更新与实时热播',functionName:'loadLatest',cacheDuration:30,params:[auSiteParam(),{name:'list',title:'片单',type:'enumeration',value:'new',enumOptions:[{title:'连载剧集更新',value:'new'},{title:'当天实时热播',value:'hot'}]}]},{id:'catalog',title:'分类片库',functionName:'loadCatalog',cacheDuration:60,params:[auSiteParam(),{name:'category',title:'分类',type:'enumeration',value:'Movie',enumOptions:AuCategories.map(function(c){return {title:c[1],value:c[0]};})},{name:'page',title:'页码',type:'page',value:'1'}]},{id:'searchList',title:'搜索（可能需要原站验证码）',functionName:'search',cacheDuration:0,params:[auSiteParam(),{name:'keyword',title:'片名',type:'input'}]},{id:'loadResource',title:'获取可用播放线路',type:'stream',functionName:'loadResource',cacheDuration:0,params:[auQualityParam()]}],
 search:{title:'Auete影视搜索',functionName:'search',params:[auSiteParam(),{name:'keyword',title:'片名',type:'input'}]}};
var auDetailFlights=Object.create(null),auResourceFlights=Object.create(null);
function auText(v){return String(v==null?'':v).replace(/<[^>]*>/g,'').replace(/\s+/g,' ').trim();}
function auSite(s){s=s||AuSites[0];if(AuSites.indexOf(s)<0)throw new Error('Auete网站入口无效');return s;}
function auUrl(u){if(typeof u!=='string'||u.length>8192||/[\s\x00-\x1f\\]/.test(u)||!/^https?:\/\/[^/@?#]+(?:[/?#]|$)/i.test(u))throw new Error('Auete资源地址无效');return u;}
function auPath(p){if(!/^\/(?:Movie|Tv|Dm|Zy|qita)\/[A-Za-z0-9_-]+\/[A-Za-z0-9_-]+\/(?:play-\d{1,3}-\d{1,5}\.html)?$/.test(p))throw new Error('Auete影片地址无效');return p;}
function auParse(link){var m=String(link).match(/^(https:\/\/[^/]+)(\/.*)$/);if(!m)throw new Error('请选择Auete模块中的影片');var site=auSite(m[1]),path=auPath(m[2]),ep=path.match(/play-(\d+)-(\d+)\.html$/);return {site:site,path:path,detail:path.replace(/play-\d+-\d+\.html$/,''),line:ep?ep[1]:null,index:ep?Number(ep[2]):null};}
function auHeaders(site){return {'User-Agent':'Mozilla/5.0',Referer:site+'/'};}
async function auGet(site,path){var r=await Widget.http.get(auSite(site)+path,{headers:auHeaders(site)}),status=Number(r.statusCode||r.status);if(status===429){var e=new Error('Auete请求过于频繁，请稍后重试');e.code='RATE_LIMIT';throw e;}if(status!==200)throw new Error('Auete入口暂不可用（HTTP '+status+'），请换入口');var t=r.data;if(typeof t!=='string'||t.length>4*1024*1024)throw new Error('Auete页面格式异常');if(/<title>[^<]*(?:安全验证|访问验证)|name=["']vdcode["']/i.test(t))throw new Error('Auete原站要求验证码，请在原站正常完成验证；模块无法自动完成或共享浏览器验证。分类浏览仍可尝试。');if(!/<html|<!doctype/i.test(t))throw new Error('Auete页面格式异常');return t;}
function auCover(v,site){v=v||'';if(v[0]==='/'&&v[1]!=='/')v=site+v;else if(v.slice(0,2)==='//')v='https:'+v;return v?auUrl(v):'';}
async function auCards(html,site){var $=await Widget.html.load(html),seen=Object.create(null),items=[];$('ul.threadlist li').each(function(i,el){var li=$(el),a=li.find('a.pic').first(),path=li.attr('data-href')||a.attr('href');if(!path)return;try{auPath(path);}catch(e){return;}if(/play-/.test(path)||seen[path])return;var img=a.find('img').first(),title=auText(li.find('h2 a').first().text()||img.attr('alt'));if(!title)return;seen[path]=true;var link=site+path,cover=auCover(img.attr('data-src')||img.attr('src'),site),rating=auText(li.find('.rating').text()).match(/(\d+(?:\.\d+)?)分/),remarks=auText(li.find('.hdtag').text()),updated=auText(li.find('.update-time').text())||li.attr('data-date')||'',cat=path.split('/')[1],item={id:link,type:'url',link:link,title:title,coverUrl:cover,posterPath:cover,rating:rating?rating[1]:'',description:[remarks,updated?'原站更新 '+updated:''].filter(Boolean).join(' · '),genreTitle:(AuCategories.find(function(c){return c[0]===cat;})||[])[1]||''};if(cat==='Movie')item.mediaType='movie';else if(cat!=='qita')item.mediaType='tv';items.push(item);});return items;}
async function loadHome(p){var site=auSite((p||{}).site);return auCards(await auGet(site,'/'),site);}
async function loadCatalog(p){p=p||{};var site=auSite(p.site),cat=p.category||'Movie',page=Number(p.page==null?1:p.page);if(!AuCategories.some(function(c){return c[0]===cat;})||!Number.isSafeInteger(page)||page<1||page>1000)throw new Error('分类或页码无效');return auCards(await auGet(site,'/'+cat+'/index'+(page===1?'':page)+'.html'),site);}
async function loadLatest(p){p=p||{};var site=auSite(p.site),list=p.list||'new';if(['new','hot'].indexOf(list)<0)throw new Error('片单无效');return auCards(await auGet(site,list==='new'?'/daynew.php':'/dayhot.php'),site);}
async function search(p){p=p||{};var site=auSite(p.site),q=auText(p.keyword);if(!q)return [];if(q.length>60)throw new Error('片名最多60字');if(Number(p.page||1)!==1)return [];return auCards(await auGet(site,'/auete4so.php?searchword='+encodeURIComponent(q)),site);}
async function auDecode(html,ids){var $=await Widget.html.load(html),title=auText($('h1.detail-title').first().text()).replace(/^《|》$/g,''),lines=[],all=Object.create(null);if(!title)throw new Error('Auete影片详情格式已变化');$('.play-card').each(function(i,el){var card=$(el),name=auText(card.find('.card-header b').first().text()),episodes=[],lineId=null;card.find('ul.episode-list a[href]').each(function(j,e){var a=$(e),path=auPath(a.attr('href')),ep=auParse(ids.site+path);if(ep.detail!==ids.detail||ep.index==null)throw new Error('Auete分集与影片不匹配');if(lineId!==null&&lineId!==ep.line)throw new Error('Auete线路分集混杂');lineId=ep.line;if(all[path])throw new Error('Auete分集地址重复');all[path]=true;episodes.push({path:path,index:ep.index,title:auText(a.text()||a.attr('title'))});});if(episodes.length){episodes.sort(function(a,b){return a.index-b.index;});episodes.forEach(function(e,i){if(e.index!==i)throw new Error('Auete分集列表不完整，请刷新详情');});if(episodes.length>10000)throw new Error('Auete分集数量异常');lines.push({id:lineId,name:name||'线路 '+lineId,episodes:episodes});}});if(!lines.length||lines.length>20)throw new Error('Auete没有可用分集');var cover=auCover($('.detail-poster img').first().attr('src'),ids.site),status=auText($('.detail-status-item').first().find('.value').text()),expected=status.match(/(?:至|更新至)\s*(\d+)\s*集/);if(expected&&Math.max.apply(null,lines.map(function(l){return l.episodes.length;}))<Number(expected[1]))throw new Error('Auete更新集数与分集列表不完整，请刷新');var item={id:ids.site+ids.detail,type:'url',link:ids.site+ids.detail,title:title,coverUrl:cover,posterPath:cover,releaseDate:auText($('.badge-time').first().text()),genreTitle:auText($('.badge-jqtype').first().text()),description:[status,auText($('.detail-des').first().text())].filter(Boolean).join('\n')};var cat=ids.detail.split('/')[1];if(cat==='Movie')item.mediaType='movie';else if(cat!=='qita')item.mediaType='tv';return {item:item,lines:lines};}
async function auDetail(ids){var key=ids.site+ids.detail;if(auDetailFlights[key])return auDetailFlights[key];auDetailFlights[key]=(async function(){return auDecode(await auGet(ids.site,ids.detail),ids);})();try{return await auDetailFlights[key];}finally{delete auDetailFlights[key];}}
async function loadDetail(link){var ids=auParse(link),d=await auDetail(ids),selected=ids.line===null?d.lines.slice().sort(function(a,b){return b.episodes.length-a.episodes.length;})[0]:d.lines.find(function(l){return l.id===ids.line;});if(!selected)throw new Error('Auete所选线路不存在');var item=d.item;item.episodeItems=selected.episodes.map(function(ep){var url=ids.site+ep.path;return {id:url,type:'url',link:url,title:ep.title,coverUrl:item.coverUrl,mediaType:item.mediaType,childItems:d.lines.filter(function(l){return l.episodes.some(function(e){return e.index===ep.index&&e.title===ep.title;});}).map(function(l){var other=l.episodes.find(function(e){return e.index===ep.index&&e.title===ep.title;}),u=ids.site+other.path;return {id:u,type:'url',link:u,title:l.name+' · '+other.title,coverUrl:item.coverUrl,mediaType:item.mediaType};})};});item.description+='\n当前线路 '+selected.name+' · '+selected.episodes.length+' 个分集';return item;}
function auBase64(s){if(!/^[A-Za-z0-9+/]+={0,2}$/.test(s)||s.length%4!==0||s.length>12000)throw new Error('Auete播放地址编码无效');var a='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/',bits=0,value=0,out='';for(var i=0;i<s.length&&s[i]!=='=';i++){value=(value<<6)|a.indexOf(s[i]);bits+=6;if(bits>=8){bits-=8;var n=(value>>bits)&255;if(n<32||n>126)throw new Error('Auete播放地址编码无效');out+=String.fromCharCode(n);}}return auUrl(out);}
async function auResources(ids,preference){if(ids.index===null)throw new Error('请先选择Auete分集');var d=await auDetail(ids),selected=d.lines.find(function(l){return l.id===ids.line;}),ep=selected&&selected.episodes.find(function(e){return e.index===ids.index;});if(!ep)throw new Error('Auete所选分集不存在');var candidates=[{line:selected,ep:ep}];d.lines.forEach(function(l){if(l.id===selected.id)return;var other=l.episodes.find(function(e){return e.index===ep.index&&e.title===ep.title;});if(other)candidates.push({line:l,ep:other});});var resources=[],seen=Object.create(null),budget={reads:0,maxReads:6},last;for(var i=0;i<Math.min(candidates.length,3);i++){var c=candidates[i];try{var html=await auGet(ids.site,c.ep.path),m=html.match(/\bvar\s+now\s*=\s*base64decode\(["']([A-Za-z0-9+/=]+)["']\)/);if(!m)throw new Error('Auete线路需要网页解析，暂不支持原生播放');var url=auBase64(m[1]);if(seen[url])continue;seen[url]=true;var info;if(/\.m3u8(?:[?#]|$)/i.test(url))info=await auHls(url,auHeaders(ids.site),preference,budget);else if(/\.mp4(?:[?#]|$)/i.test(url))info={url:url};else throw new Error('Auete未提供支持的直连格式');var name=c.line.name+' · '+ep.title;if(info.height)name+=' · 清单 '+info.width+'×'+info.height;if(info.fixed)name+=' · 固定';if(info.retained&&preference==='fixed')name+=' · 自适应（保留音轨/字幕）';resources.push({name:name,url:info.url,playerType:'app',customHeaders:auHeaders(ids.site),description:'Auete原站同一分集；画质以实际播放清单为准'});}catch(e){if(e.code==='RATE_LIMIT')throw e;last=e;}if(budget.reads>=budget.maxReads)break;}if(!resources.length)throw last||new Error('Auete暂无可用播放线路');return resources;}
async function loadResource(p){p=typeof p==='string'?{link:p}:p||{};var ids=auParse(p.link),preference=p.qualityPreference||'highest';if(['highest','fixed'].indexOf(preference)<0)throw new Error('画质选项无效');var key=p.link+'|'+preference;if(auResourceFlights[key])return auResourceFlights[key];auResourceFlights[key]=auResources(ids,preference);try{return await auResourceFlights[key];}finally{delete auResourceFlights[key];}}

// Bounded HLS inspection; keep external audio and subtitle groups intact.
function auRelative(base,ref){if(/^https?:\/\//i.test(ref))return auUrl(ref);if(/^\/\//.test(ref))return auUrl(base.split(':')[0]+':'+ref);if(/^[a-z][a-z\d+.-]*:/i.test(ref)||/[\s\\]/.test(ref))throw new Error('播放清单地址无效');var m=base.match(/^(https?:\/\/[^/]+)(\/[^?#]*)?/i);if(!m)throw new Error('播放清单地址无效');if(ref.charAt(0)==='?')return m[1]+(m[2]||'/')+ref;var path=ref.charAt(0)==='/'?ref:(m[2]||'/').replace(/[^/]*$/,'')+ref,parts=[];path.split('/').forEach(function(p){if(p==='..')parts.pop();else if(p!=='.')parts.push(p);});return auUrl(m[1]+parts.join('/'));}
async function auHls(url,headers,preference,budget){var seen=Object.create(null),reads=0;
 async function read(u,depth,keep){if(depth>=3||++reads>5||seen[u])throw new Error('播放清单检查达到上限');seen[u]=true;if(budget){if(budget.reads>=budget.maxReads)throw new Error('播放清单检查达到总请求上限');budget.reads++;}var r=await Widget.http.get(u,{headers:headers}),s=Number(r.statusCode||r.status);if(s===429){var e=new Error('播放线路请求过于频繁，请稍后重试');e.code='RATE_LIMIT';throw e;}var text=r.data;if(s!==200||typeof text!=='string'||text.length>1024*1024||!/^\s*#EXTM3U/.test(text))throw new Error('Auete影视所选画质清单不可用，请稍后重试');var lines=text.split(/\r?\n/).map(function(l){return l.trim();});if(!/#EXT-X-STREAM-INF:/.test(text)){if(!/#EXTINF:/.test(text)||!lines.some(function(l){return l&&l[0]!=='#';}))throw new Error('播放清单为空');return {url:u};}
 var external=/(?:[:,])(?:AUDIO|SUBTITLES|VIDEO|CLOSED-CAPTIONS)=(?!NONE(?:,|\r?\n|$))/.test(text),variants=[];
 for(var i=0;i<lines.length;i++)if(/^#EXT-X-STREAM-INF:/.test(lines[i])){var res=lines[i].match(/RESOLUTION=(\d+)x(\d+)/),bw=lines[i].match(/(?:[:,])BANDWIDTH=(\d+)/);for(var j=i+1;j<lines.length;j++){if(/^#EXT-X-STREAM-INF:/.test(lines[j]))break;if(lines[j]&&lines[j][0]!=='#'){variants.push({url:auRelative(u,lines[j]),width:res?Number(res[1]):0,height:res?Number(res[2]):0,bw:bw?Number(bw[1]):0});break;}}}
 variants.sort(function(a,b){return b.width*b.height-a.width*a.height||b.bw-a.bw;});var last;
 for(var v=0;v<Math.min(variants.length,2);v++)try{var chosen=variants[v],child=await read(chosen.url,depth+1,keep||external),fixed=preference==='fixed'&&!keep&&!external&&!child.retained;
 if(v===0&&child.url===chosen.url){return {url:fixed?child.url:u,width:chosen.width,height:chosen.height,fixed:fixed,retained:external||keep||child.retained};}
 if(keep||external)throw new Error('备用清单有独立音轨或字幕，请选择其他来源');return {url:child.url,width:chosen.width,height:chosen.height,fixed:fixed,retained:child.retained};}catch(e){if(e.code==='RATE_LIMIT')throw e;last=e;}
 throw last||new Error('播放子清单不可用');
 }return read(url,0,false);
}
