// Eboyang public pages and JSON string literals only; never execute remote scripts.
var EB_SITE='https://www.eboyang.com',EbCategories=[['1','电影'],['2','电视剧'],['3','综艺'],['4','动漫'],['30','短剧']],ebDetails=Object.create(null),ebStreams=Object.create(null);
var WidgetMetadata={id:'joeshu.eboyang',title:'Eboyang影视',author:'joeshu',site:EB_SITE,version:'0.1.0',requiredVersion:'0.0.1',description:'独立首页、近期更新、五类片库与完整分集；搜索、分页及播放受原站可用性影响。',detailCacheDuration:0,modules:[{id:'home',title:'首页推荐',functionName:'loadHome',cacheDuration:60,params:[]},{id:'latest',title:'原站近期更新',functionName:'loadLatest',cacheDuration:30,params:[]},{id:'catalog',title:'分类片库',functionName:'loadCatalog',cacheDuration:60,params:[{name:'category',title:'分类',type:'enumeration',value:'2',enumOptions:EbCategories.map(function(c){return {title:c[1],value:c[0]};})},{name:'page',title:'页码',type:'page',value:'1'}]},{id:'searchList',title:'搜索影片',functionName:'search',cacheDuration:0,params:[{name:'keyword',title:'片名',type:'input'}]},{id:'loadResource',title:'获取可用线路',type:'stream',functionName:'loadResource',cacheDuration:0,params:[{name:'qualityPreference',title:'画质',type:'enumeration',value:'highest',enumOptions:[{title:'最高可用（自适应）',value:'highest'},{title:'固定高画质',value:'fixed'}]}]}],search:{title:'Eboyang影视搜索',functionName:'search',params:[{name:'keyword',title:'片名',type:'input'}]}};
function ebText(v){return String(v==null?'':v).replace(/<[^>]*>/g,'').replace(/\s+/g,' ').trim();}
function ebUrl(u){if(typeof u!=='string'||u.length>8192||/[\s\x00-\x1f\\]/.test(u)||!/^https:\/\/[^/@?#]+(?:[/?#]|$)/i.test(u))throw new Error('Eboyang资源地址无效或不是HTTPS');return u;}
function ebParse(u){var m=String(u).match(/^https:\/\/www\.eboyang\.com\/(?:bovod\/(\d{1,10})|bovideo\/(\d{1,10})-(\d{1,3})-(\d{1,5}))\.html$/);if(!m)throw new Error('请选择Eboyang模块中的影片或分集');return {id:m[1]||m[2],sid:m[3]||null,index:m[4]==null?null:Number(m[4]),path:String(u).slice(EB_SITE.length)};}
function ebHeaders(){return {'User-Agent':'Mozilla/5.0',Referer:EB_SITE+'/'};}
function ebStatus(r){var s=Number(r.statusCode||r.status);if(s===429){var e=new Error('Eboyang请求过于频繁，请稍后重试');e.code='RATE_LIMIT';throw e;}if(s!==200)throw new Error('Eboyang暂不可用（HTTP '+s+'）');return r.data;}
async function ebGet(path){var r;try{r=await Widget.http.get(EB_SITE+path,{headers:ebHeaders()});}catch(e){if(/TLS|SSL|secure|安全连接|证书|-120[0-6]/i.test(String(e.message||e)))throw new Error('Eboyang HTTPS连接失败，请检查网络、代理或HTTPS解密；浏览器会话不一定与App共享');throw e;}var s=ebStatus(r);if(typeof s!=='string'||s.length>6*1024*1024||!/<html|<!doctype/i.test(s))throw new Error('Eboyang页面格式异常');if(/<title>[^<]*(?:Just a moment|安全验证)|name=["'](?:verify|vdcode)["']/i.test(s))throw new Error('Eboyang原站要求验证，请到原站正常完成；模块不能自动完成验证');return s;}
function ebCover(u){u=u||'';if(u.slice(0,2)==='//')u='https:'+u;else if(u[0]==='/')u=EB_SITE+u;try{return u?ebUrl(u):'';}catch(e){return '';}}
async function ebCards(html,category){var $=await Widget.html.load(html),out=[],seen=Object.create(null);$('li.fed-list-item, .fed-deta-info').each(function(i,e){var li=$(e),a=li.find('a.fed-list-pics').first(),path=a.attr('href'),title=ebText(li.find('.fed-list-title').first().text()||li.find('h1,h2,h3').first().text()),ids;try{ids=ebParse(EB_SITE+path);}catch(e){return;}if(ids.sid||seen[ids.id]||!title)return;seen[ids.id]=true;var link=EB_SITE+path,cover=ebCover(a.attr('data-original')||a.find('img').attr('data-original')||a.find('img').attr('src')),item={id:link,type:'url',link:link,title:title,coverUrl:cover,posterPath:cover,description:ebText(li.find('.fed-list-remarks').text())};if(category)item.mediaType=category==='1'?'movie':'tv';out.push(item);});return out;}
async function loadHome(){return ebCards(await ebGet('/'));}
async function loadLatest(){var $=await Widget.html.load(await ebGet('/')),section=null;$('h2').each(function(i,e){if(ebText($(e).text())==='最近更新')section=$(e).parent().parent();});if(!section)throw new Error('Eboyang近期更新区结构已变化');return ebCards(section.toString());}
async function loadCatalog(p){p=p||{};var c=String(p.category||'2'),n=Number(p.page==null?1:p.page);if(!EbCategories.some(function(x){return x[0]===c;})||!Number.isSafeInteger(n)||n<1||n>2000)throw new Error('分类或页码无效');return ebCards(await ebGet('/vodlist/'+c+(n===1?'':'-'+n)+'.html'),c);}
async function search(p){p=p||{};var q=ebText(p.keyword);if(!q)return [];if(q.length>60)throw new Error('关键词最多60字');if(Number(p.page||1)!==1)return [];return ebCards(await ebGet('/search.php?searchword='+encodeURIComponent(q)));}
async function ebDecode(html,ids){var $=await Widget.html.load(html),a=$('h1 a[href="/bovod/'+ids.id+'.html"]').first(),title=ebText(a.text());if(!title)throw new Error('Eboyang详情与所选影片不匹配');var lines=[],seen=Object.create(null);$('dd[id^="playList"]').each(function(i,e){var box=$(e),list=[],sid=null;box.find('a[href^="/bovideo/"]').each(function(j,e){var a=$(e),ep=ebParse(EB_SITE+a.attr('href'));if(ep.id!==ids.id||ep.index===null)throw new Error('Eboyang分集与影片不匹配');if(sid!==null&&sid!==ep.sid)throw new Error('Eboyang线路混杂');sid=ep.sid;if(seen[ep.path])throw new Error('Eboyang分集地址重复');seen[ep.path]=true;list.push({path:ep.path,index:ep.index,title:ebText(a.attr('title')||a.text())});});if(!list.length)return;list.sort(function(a,b){return a.index-b.index;});list.forEach(function(e,i){if(e.index!==i||!e.title)throw new Error('Eboyang分集列表不完整');});if(list.length>10000)throw new Error('Eboyang分集数量异常');var key=(box.attr('class')||'').split(/\s+/)[0],tab=$('.tabt3 span').filter(function(i,e){return $(e).attr('id')===key;}).first(),badge=ebText(tab.find('sup').text()).match(/^(\d+)集$/),name=ebText(tab.clone().find('sup').remove().end().text());if(badge&&Number(badge[1])!==list.length)throw new Error('Eboyang线路标注集数与列表不符');lines.push({sid:sid,name:name||'线路 '+sid,episodes:list});});if(!lines.length||lines.length>20)throw new Error('Eboyang没有可用分集');var link=EB_SITE+'/bovod/'+ids.id+'.html',cover=ebCover($('.qqmt5-deta-images a').first().attr('data-original')),meta=$('.qqmt5-deta-content').first(),year='',genre='';meta.find('li').each(function(i,e){var t=ebText($(e).text());if(t.startsWith('年份：'))year=t.slice(3);if(t.startsWith('分类：'))genre=t.slice(3);});var item={id:link,type:'url',link:link,title:title,coverUrl:cover,posterPath:cover,releaseDate:year,genreTitle:genre,description:ebText($('.yno5-drop-boxs').first().text())};if(/剧|动漫|综艺/.test(genre))item.mediaType='tv';else if(/片|电影/.test(genre))item.mediaType='movie';return {item:item,lines:lines};}
async function ebDetail(ids){if(ebDetails[ids.id])return ebDetails[ids.id];ebDetails[ids.id]=(async function(){return ebDecode(await ebGet('/bovod/'+ids.id+'.html'),ids);})();try{return await ebDetails[ids.id];}finally{delete ebDetails[ids.id];}}
async function loadDetail(link){var ids=ebParse(link),d=await ebDetail(ids),line=ids.sid?d.lines.find(function(l){return l.sid===ids.sid;}):d.lines.slice().sort(function(a,b){return b.episodes.length-a.episodes.length;})[0];if(!line)throw new Error('Eboyang所选线路不存在');var item=Object.assign({},d.item);item.episodeItems=line.episodes.map(function(ep){var link=EB_SITE+ep.path;return {id:link,type:'url',link:link,title:ep.title,coverUrl:item.coverUrl,mediaType:item.mediaType,childItems:d.lines.map(function(l){var e=l.episodes.find(function(x){return x.index===ep.index&&x.title===ep.title;});if(!e)return null;var link=EB_SITE+e.path;return {id:link,type:'url',link:link,title:l.name+' · '+e.title,coverUrl:item.coverUrl,mediaType:item.mediaType};}).filter(Boolean)};});return item;}
function ebPlayer(html,ids){var m=html.match(/<script[^>]*>\s*var vid=("[^"<>]*");\s*var vfrom=("[^"<>]*");\s*var vpart=("[^"<>]*");\s*var now=("[^"<>]*");/);if(!m)throw new Error('Eboyang线路需要网页解析，暂未支持');var v=m.slice(1).map(function(s){return JSON.parse(s);});if(v[0]!==ids.id||v[1]!==ids.sid||Number(v[2])!==ids.index)throw new Error('Eboyang播放参数与分集不匹配');return ebUrl(v[3]);}
async function ebResources(ids,quality){if(!ids.sid)throw new Error('请先选择Eboyang分集');var d=await ebDetail(ids),selected=d.lines.find(function(l){return l.sid===ids.sid;}),ep=selected&&selected.episodes.find(function(e){return e.index===ids.index;});if(!ep)throw new Error('Eboyang分集不存在');var candidates=[{line:selected,ep:ep}];d.lines.forEach(function(l){if(l.sid===selected.sid)return;var other=l.episodes.find(function(e){return e.index===ep.index&&e.title===ep.title;});if(other)candidates.push({line:l,ep:other});});var out=[],seen=Object.create(null),last,errors=[],budget={reads:0,maxReads:6};for(var i=0;i<Math.min(candidates.length,3);i++)try{var c=candidates[i],page=await ebGet(c.ep.path),url=ebPlayer(page,ebParse(EB_SITE+c.ep.path)),headers=ebHeaders(),code=ebPlayerCode(page);if(code==='vip'){url=await ebSigned(url,code,c.ep.path);headers.Referer='https://tv.qingning88.com/';}if(seen[url])continue;seen[url]=true;var info;if(/\.m3u8(?:[?#]|$)/i.test(url))info=await ebHls(url,headers,quality,budget);else if(/\.mp4(?:[?#]|$)/i.test(url))info=await ebMp4(url,headers);else throw new Error('Eboyang线路未提供可用M3U8或MP4直连');var name=c.line.name+' · '+ep.title;if(info.height)name+=' · 清单 '+info.width+'×'+info.height;if(info.fixed)name+=' · 固定';if(info.retained&&quality==='fixed')name+=' · 自适应（保留音轨/字幕）';out.push({name:name,url:info.url,playerType:'app',customHeaders:headers});}catch(e){if(e.code==='RATE_LIMIT')throw e;last=e;errors.push(c.line.name+'：'+String(e.message||e).replace(/https?:\/\/\S+/g,'[资源地址]'));}if(!out.length)throw new Error('Eboyang线路检查失败（'+errors.join('；')+'），可选择分集的其他线路重试');return out;}
async function loadResource(p){p=typeof p==='string'?{link:p}:p||{};var ids=ebParse(p.link),q=p.qualityPreference||'highest';if(['highest','fixed'].indexOf(q)<0)throw new Error('画质选项无效');var key=p.link+'|'+q;if(ebStreams[key])return ebStreams[key];ebStreams[key]=ebResources(ids,q);try{return await ebStreams[key];}finally{delete ebStreams[key];}}

// Bounded HLS inspection; keep external audio and subtitle groups intact.
function ebRelative(base,ref){if(/^https?:\/\//i.test(ref))return ebUrl(ref);if(/^\/\//.test(ref))return ebUrl(base.split(':')[0]+':'+ref);if(/^[a-z][a-z\d+.-]*:/i.test(ref)||/[\s\\]/.test(ref))throw new Error('播放清单地址无效');var m=base.match(/^(https?:\/\/[^/]+)(\/[^?#]*)?/i);if(!m)throw new Error('播放清单地址无效');if(ref.charAt(0)==='?')return m[1]+(m[2]||'/')+ref;var path=ref.charAt(0)==='/'?ref:(m[2]||'/').replace(/[^/]*$/,'')+ref,parts=[];path.split('/').forEach(function(p){if(p==='..')parts.pop();else if(p!=='.')parts.push(p);});return ebUrl(m[1]+parts.join('/'));}
async function ebHls(url,headers,preference,budget){var seen=Object.create(null),reads=0;
 async function read(u,depth,keep){if(depth>=3||++reads>5||seen[u])throw new Error('播放清单检查达到上限');seen[u]=true;if(budget){if(budget.reads>=budget.maxReads)throw new Error('播放清单检查达到总请求上限');budget.reads++;}var r=await Widget.http.get(u,{headers:headers}),s=Number(r.statusCode||r.status);if(s===429){var e=new Error('播放线路请求过于频繁，请稍后重试');e.code='RATE_LIMIT';throw e;}var text=r.data;if(s!==200||typeof text!=='string'||text.length>1024*1024||!/^\s*#EXTM3U/.test(text))throw new Error('Eboyang影视所选画质清单不可用，请稍后重试');var lines=text.split(/\r?\n/).map(function(l){return l.trim();});if(!/#EXT-X-STREAM-INF:/.test(text)){if(!/#EXTINF:/.test(text)||!lines.some(function(l){return l&&l[0]!=='#';}))throw new Error('播放清单为空');return {url:u};}
 var external=/(?:[:,])(?:AUDIO|SUBTITLES|VIDEO|CLOSED-CAPTIONS)=(?!NONE(?:,|\r?\n|$))/.test(text),variants=[];
 for(var i=0;i<lines.length;i++)if(/^#EXT-X-STREAM-INF:/.test(lines[i])){var res=lines[i].match(/RESOLUTION=(\d+)x(\d+)/),bw=lines[i].match(/(?:[:,])BANDWIDTH=(\d+)/);for(var j=i+1;j<lines.length;j++){if(/^#EXT-X-STREAM-INF:/.test(lines[j]))break;if(lines[j]&&lines[j][0]!=='#'){variants.push({url:ebRelative(u,lines[j]),width:res?Number(res[1]):0,height:res?Number(res[2]):0,bw:bw?Number(bw[1]):0});break;}}}
 variants.sort(function(a,b){return b.width*b.height-a.width*a.height||b.bw-a.bw;});var last;
 for(var v=0;v<Math.min(variants.length,2);v++)try{var chosen=variants[v],child=await read(chosen.url,depth+1,keep||external),fixed=preference==='fixed'&&!keep&&!external&&!child.retained;
 if(v===0&&child.url===chosen.url){return {url:fixed?child.url:u,width:chosen.width,height:chosen.height,fixed:fixed,retained:external||keep||child.retained};}
 if(keep||external)throw new Error('备用清单有独立音轨或字幕，请选择其他来源');return {url:child.url,width:chosen.width,height:chosen.height,fixed:fixed,retained:child.retained};}catch(e){if(e.code==='RATE_LIMIT')throw e;last=e;}
 throw last||new Error('播放子清单不可用');
 }return read(url,0,false);
}

async function ebMp4(url,headers){if(typeof Widget.http.request!=='function')throw new Error('当前App不支持MP4媒体检查，请更新App');var r=await Widget.http.request({url:url,method:'HEAD',headers:headers||ebHeaders()}),status=Number(r.statusCode||r.status),ct='';if(status===429){var e=new Error('Eboyang线路请求过于频繁，请稍后重试');e.code='RATE_LIMIT';throw e;}Object.keys(r.headers||{}).forEach(function(k){if(k.toLowerCase()==='content-type')ct=String(r.headers[k]);});if(status!==200||!/^video\/mp4(?:;|$)/i.test(ct))throw new Error('Eboyang线路未返回有效MP4媒体');return {url:url};}

function ebPlayerCode(html){var m=html.match(/var now="[^"<>]*";\s*var pn=("[A-Za-z0-9_-]{1,30}");/);return m?JSON.parse(m[1]):null;}
async function ebSigned(url,code,path){if(code!=='vip')throw new Error('Eboyang未支持此网页解析线路');var endpoint='https://tv.qingning88.com/api/publicApi.php?url='+encodeURIComponent(url).replace(/%3A/gi,':').replace(/%2F/gi,'/')+'&code='+code,r=await Widget.http.get(endpoint,{headers:{'User-Agent':'Mozilla/5.0',Referer:EB_SITE+path}}),html=ebStatus(r);if(typeof html!=='string'||html.length>1024*1024)throw new Error('Eboyang原站播放器响应异常');var m=html.match(/\bvar url = '(https:\/\/[^'\\\s<>]+)';/);if(!m)throw new Error('Eboyang原站未返回签发资源');var signed=ebUrl(m[1]);if(signed.split('?')[0]!==url.split('?')[0])throw new Error('Eboyang签发资源与所选分集不匹配');return signed;}
