// Production requests through the official Rex adapter. Reports never include
// cookies, visitor IDs, episode tokens or signed playback URLs.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process'),{pathToFileURL}=require('node:url');
function request(url,options={}){return new Promise((resolve,reject)=>{const child=spawn('python3',[path.join(__dirname,'http-bridge.py')],{stdio:['pipe','pipe','pipe']});let output='';child.stdout.on('data',x=>output+=x);child.on('error',reject);child.on('close',code=>{if(code)return reject(Error('Transport failed'));try{const r=JSON.parse(output);resolve(new Response(Buffer.from(r.bodyBase64,'base64'),{status:r.status,headers:r.headers}));}catch(e){reject(Error('Invalid transport response'));}});child.stdin.end(JSON.stringify({url:String(url),method:options.method||'GET',headers:options.headers||{},body:options.body}));});}
(async()=>{
 const {WidgetAdaptor}=await import('./node_modules/@rexnow/libs/dist/widget-adaptor.js');
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'souju-schema-')),file=path.join(tmp,'schema.mjs');
 const schema=fs.readFileSync(__dirname+'/node_modules/@rexnow/libs/dist/env.zod/index.ts','utf8').replace('from "zod"','from '+JSON.stringify(pathToFileURL(__dirname+'/node_modules/zod/index.js').href)).replace(/: z\.ZodTypeAny/g,'');fs.writeFileSync(file,schema);const schemas=await import(pathToFileURL(file));
 globalThis.fetch=request;const values={};const c=vm.createContext({Widget:{...WidgetAdaptor,storage:{get:async k=>values[k],set:async(k,v)=>values[k]=v}}});vm.runInContext(fs.readFileSync(__dirname+'/souju.js','utf8'),c);
 const report={time:new Date().toISOString(),version:c.WidgetMetadata.version,sourceSha256:require('node:crypto').createHash('sha256').update(fs.readFileSync(__dirname+'/souju.js')).digest('hex'),checks:[],limitations:'Native iPhone import/playback not tested; samples do not establish all titles or all lines as playable. Parser/quota lines are not invoked. Latest resource timestamps indicate catalogue updates, not release dates; each page is ordered by its returned timestamps.'};
 async function check(name,fn){try{const result=await fn();report.checks.push({name,status:'PASS',result});console.log('PASS '+name+' '+JSON.stringify(result));return result;}catch(e){report.checks.push({name,status:'FAIL',error:e.message});throw e;}finally{fs.writeFileSync(__dirname+'/souju-validation.json',JSON.stringify(report,null,2)+'\n');}}
 function videos(items){items.forEach(i=>schemas.videoItemSchema.parse(i));return items;}
 try{
 await check('official metadata schema',()=>{schemas.widgetMetadataSchema.parse(c.WidgetMetadata);return true;});
 await check('empty search is idle',async()=>{assert.equal((await c.search({})).length,0);assert.equal(Object.keys(values).length,0);return true;});
 let home;await check('anonymous session and home recommendations',async()=>{home=videos(await c.loadHome());assert(home.length>0);return {count:home.length};});
 await check('six named categories and numbered pagination',async()=>{const results=await Promise.all(['movie','series','anime','variety','short_drama','documentary'].map(async kind=>{const items=videos(await c.loadCatalog({kind}));assert(items.length>0);return {kind,count:items.length};}));const a=await c.loadCatalog({kind:'movie'}),b=videos(await c.loadCatalog({kind:'movie',page:2}));assert(b.length>0);assert.notEqual(a[0].id,b[0].id);return results;});
 await check('combined genre/region/year filters',async()=>{const filters=[{kind:'movie',genre:'科幻'},{kind:'series',area:'韩国',year:'current'},{kind:'documentary',genre:'自然'}];return Promise.all(filters.map(async f=>{const items=videos(await c.loadCatalog(f));assert(items.length>0);for(const item of items){if(f.genre)assert(item.genreTitle.includes(f.genre));if(f.area)assert(item.description.includes(f.area));if(f.year)assert.equal(item.releaseDate,String(c.sjYear()));}return {kind:f.kind,genre:f.genre||'',area:f.area||'',year:f.year||'',count:items.length};}));});
 await check('latest updates and dynamic current-year releases',async()=>{const [updates,current]=await Promise.all([c.loadLatest({kind:'series'}),c.loadLatest({kind:'movie',period:'current'})]);videos(updates);videos(current);assert(updates.length>0&&current.length>0);assert(current.every(x=>Number(x.releaseDate)===c.sjYear()));assert(updates.every(x=>!x.releaseDate||Number(x.releaseDate)<=c.sjYear()));assert(updates.some(x=>x.description.includes('北京时间')));return {updates:updates.length,currentYear:c.sjYear(),newMovies:current.length};});
 await check('named recommendation topics and weekly trending',async()=>{const topics=['tv_domestic','tv_american','movie_hot'];const results=await Promise.all(topics.map(async topic=>{const items=videos(await c.loadHome({topic}));assert(items.length>0);return {topic,count:items.length};}));const weekly=videos(await c.loadTrending({kind:'series',window:'week'}));assert(weekly.length>0);return {topics:results,weeklyCount:weekly.length};});
 let found;await check('actual title search uses q and catalog_search',async()=>{found=videos(await c.search({keyword:'流浪地球'}));assert(found.some(i=>i.title==='流浪地球2'));assert(found[0].title.includes('流浪地球'));return {count:found.length,titles:found.slice(0,3).map(i=>i.title)};});
 let detail,seriesDetail;await check('movie and series details with coherent episodes',async()=>{detail=await c.loadDetail(found.find(i=>i.title==='流浪地球2').link);schemas.videoItemSchema.parse(detail);assert(detail.episodeItems.length>0);const tv=home.find(i=>i.mediaType==='tv'),td=seriesDetail=await c.loadDetail(tv.link);schemas.videoItemSchema.parse(td);assert(td.episodeItems.length>1);return {movieEpisodes:detail.episodeItems.length,seriesTitle:td.title,seriesEpisodes:td.episodeItems.length};});
 let sources;await check('manual playback returns all visitor direct media',async()=>{sources=await c.loadResource({link:detail.episodeItems[0].link,lineMode:'all'});assert(sources.length>0);sources.forEach(s=>{schemas.streamSourceItemSchema.parse(s);assert(/^https?:/.test(s.url));assert(!s.customHeaders.Cookie);});return {directLineCount:sources.length,names:sources.slice(0,5).map(s=>s.name)};});
 await check('automatic movie and series line selection checks HLS',async()=>{const movie=await c.loadResource({link:detail.episodeItems[0].link});const series=await c.loadResource({link:seriesDetail.episodeItems[0].link});for(const items of [movie,series]){assert(items.length>0&&items.length<=3);items.forEach(x=>{schemas.streamSourceItemSchema.parse(x);assert(x.description.includes('清单已检查'));});}return {movieVerifiedLines:movie.length,seriesVerifiedLines:series.length,movieNames:movie.map(x=>x.name),seriesNames:series.map(x=>x.name)};});
 await check('sample HLS manifest is readable',async()=>{let tried=0;const failures=[];for(const s of sources.filter(s=>/\.m3u8(?:\?|$)/.test(s.url)).slice(0,4)){tried++;try{const r=await WidgetAdaptor.http.get(s.url,{headers:s.customHeaders});if(r.statusCode===200&&String(r.data).trim().startsWith('#EXTM3U'))return {name:s.name,status:200,attempted:tried};failures.push(r.statusCode);}catch(e){failures.push('transport');}}throw Error('Sample HLS checks failed: '+failures.join(','));});
 }finally{fs.rmSync(tmp,{recursive:true,force:true});}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
