// Read-only production verification. Never calls resolve-line or stores signed URLs in the report.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawn}=require('node:child_process'),{pathToFileURL}=require('node:url');
function request(url,opts={}){return new Promise((resolve,reject)=>{const p=spawn('python3',[path.join(__dirname,'http-bridge.py')],{stdio:['pipe','pipe','pipe']});let output='';p.stdout.on('data',x=>output+=x);p.on('error',reject);p.on('close',code=>{if(code)return reject(Error('HTTPS transport failed'));try{const r=JSON.parse(output);resolve(new Response(Buffer.from(r.bodyBase64,'base64'),{status:r.status,headers:r.headers}));}catch{reject(Error('Invalid transport response'));}});p.stdin.end(JSON.stringify({url:String(url),method:opts.method||'GET',headers:opts.headers||{},body:opts.body}));});}
(async()=>{
 const {WidgetAdaptor}=await import('./node_modules/@rexnow/libs/dist/widget-adaptor.js');globalThis.fetch=request;const values={};
 // Optional development checkpoint preserves the one guest created during protocol inspection.
 if(process.env.KANJU_DEV_SESSION){const state=JSON.parse(fs.readFileSync(process.env.KANJU_DEV_SESSION,'utf8'));values['kanju.visitor']=JSON.stringify(state.visitor);values['kanju.session']=JSON.stringify({cookie:state.cookie,expires:state.expires||Date.now()+3600000});}
 const c=vm.createContext({Widget:{...WidgetAdaptor,storage:{get:async k=>values[k],set:async(k,v)=>values[k]=v}}});const code=fs.readFileSync(__dirname+'/kanju.js','utf8');vm.runInContext(code,c);
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'kanju-schema-')),schemaFile=path.join(temp,'schema.mjs');
 const schema=fs.readFileSync(__dirname+'/node_modules/@rexnow/libs/dist/env.zod/index.ts','utf8').replace('from "zod"','from '+JSON.stringify(pathToFileURL(__dirname+'/node_modules/zod/index.js').href)).replace(/: z\.ZodTypeAny/g,'');fs.writeFileSync(schemaFile,schema);const schemas=await import(pathToFileURL(schemaFile));
 const report={time:new Date().toISOString(),version:c.WidgetMetadata.version,site:c.SOUJU.site,sourceSha256:crypto.createHash('sha256').update(code).digest('hex'),checks:[],limitations:'Read-only real API and HLS manifest samples; no AI resolve-line call, video segment download, complete media decoding or native iOS layout test. No visitor IDs, cookies, tickets or playback URLs in this report.'};
 async function check(name,fn){try{const result=await fn();report.checks.push({name,passed:true,result});console.log('PASS '+name+' '+JSON.stringify(result));return result;}catch(error){report.checks.push({name,passed:false,error:'Sample verification failed; see runtime error type: '+error.name});throw error;}}
 try{
  await check('official Rex metadata schema',()=>{schemas.widgetMetadataSchema.parse(c.WidgetMetadata);return true;});
  const baseline=await c.kjReadQuota();await check('real guest quota and Beijing reset',()=>({limit:baseline.limit_tokens,remaining:baseline.remaining_tokens,usageDate:baseline.usage_date,resetBeijing:new Date(Date.parse(baseline.reset_at)+8*3600000).toISOString().slice(0,19)}));
  await check('home public preview',async()=>{const items=await c.loadHome();assert(items.length);items.forEach(x=>schemas.videoItemSchema.parse(x));return {cards:items.length};});
  for(const kind of ['movie','series','anime','variety','short_drama','documentary'])await check('category '+kind,async()=>{const items=await c.loadCatalog({kind});items.forEach(x=>schemas.videoItemSchema.parse(x));assert(items.length);return {cards:items.length};});
  await check('latest, combined filters and trending',async()=>{const latest=await c.loadLatest({kind:'anime'}),filtered=await c.loadCatalog({kind:'movie',genre:'科幻',area:'美国',year:'current'}),trending=await c.loadTrending({kind:'series',window:'day'});assert(latest.length&&trending.length);return {latest:latest.length,filtered:filtered.length,trending:trending.length};});
  const found=await c.search({keyword:'凡人修仙传'}),hit=found.find(x=>x.title==='凡人修仙传'&&x.releaseDate==='2020');assert(hit);const detail=await c.loadDetail(hit.link);
  await check('complete current available season including after episode 100',()=>{schemas.videoItemSchema.parse(detail);assert(detail.episodeItems.length>100);assert.equal(new Set(detail.episodeItems.map(x=>x.id)).size,detail.episodeItems.length);assert(detail.episodeItems[100].link.endsWith('offset=100'));return {title:detail.title,available:detail.episodeItems.length,boundary:detail.episodeItems[100].title,last:detail.episodeItems.at(-1).title};});
  for(const index of [100,detail.episodeItems.length-1])await check('direct HLS sample '+detail.episodeItems[index].title,async()=>{const streams=await c.loadResource({link:detail.episodeItems[index].link});assert(streams.length);streams.forEach(x=>schemas.streamSourceItemSchema.parse(x));assert(streams.every(x=>x.description.includes('清单已检查')));return {lines:streams.length,names:streams.map(x=>x.name)};});
  await check('real quota status schema',async()=>{const [status]=await c.loadAiQuotaStatus();schemas.videoItemSchema.parse(status);assert(status.description.includes('原站剩余'));return {title:status.title,hasServerQuota:true};});
  const after=await c.kjReadQuota();await check('no AI tokens spent by this validation',()=>{assert.equal(after.used_tokens,baseline.used_tokens);assert.equal(after.reserved_tokens,baseline.reserved_tokens);return {usedBefore:baseline.used_tokens,usedAfter:after.used_tokens};});
 }finally{fs.writeFileSync(__dirname+'/kanju-validation.json',JSON.stringify(report,null,2)+'\n');fs.rmSync(temp,{recursive:true,force:true});}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
