const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const site='https://www.eboyang.com',detailLink=site+'/bovod/1.html',epLink=site+'/bovideo/1-1-0.html';
function fixture(n=195){let a='';for(let i=0;i<n;i++)a+=`<a href="/bovideo/1-1-${i}.html">第${i+1}集</a>`;return `<html><h1><a href="/bovod/1.html">片名</a></h1><div class="tabt3"><span id="vip">秒播<sup>${n}集</sup></span></div><dd id="playList2" class="vip">${a}</dd></html>`;}
function player(url,id='1',sid='1',index='0'){return `<html><script>var vid="${id}";var vfrom="${sid}";var vpart="${index}";var now=${JSON.stringify(url)};</script></html>`;}
(async()=>{const {WidgetAdaptor}=await import('./node_modules/@rexnow/libs/dist/widget-adaptor.js');let passed=0;function ctx(handler){const requests=[];const call=async(m,u,o)=>{requests.push({m,u,o});return handler(m,u,o);};const c=vm.createContext({Widget:{html:WidgetAdaptor.html,http:{get:(u,o)=>call('GET',u,o),request:o=>call(o.method,o.url,o)}}});vm.runInContext(fs.readFileSync('eboyang.js','utf8'),c);return {c,requests};}const html=data=>({statusCode:200,data});async function test(n,f){await f();passed++;console.log('PASS '+n);}
await test('immutable snapshot matches',()=>assert.equal(fs.readFileSync('eboyang.js','utf8'),fs.readFileSync('eboyang-0.1.0.js','utf8')));
await test('strict original links and zero based episodes',()=>{const {c}=ctx(()=>html(''));assert.equal(c.ebParse(epLink).index,0);for(const u of ['https://evil.test/bovod/1.html',site+'/bovod/1.html?x=1',site+'/bovideo/1-1--1.html'])assert.throws(()=>c.ebParse(u));assert.throws(()=>c.ebUrl('http://media.test/a.m3u8'));});
await test('category pagination and search encoded without duplicate pages',async()=>{const {c,requests}=ctx(()=>html('<html></html>'));await c.loadCatalog({category:'30',page:2});assert.equal(requests[0].u,site+'/vodlist/30-2.html');await c.search({keyword:'a&b'});assert.equal(requests[1].u,site+'/search.php?searchword=a%26b');assert.equal((await c.search({keyword:'x',page:2})).length,0);assert.equal(requests.length,2);await assert.rejects(c.loadCatalog({page:0}));});
await test('home cards deduplicate and recent updates excludes recommendations',async()=>{const a='<li class="fed-list-item"><a class="fed-list-pics" href="/bovod/1.html" data-original="//img.test/a.jpg"></a><a class="fed-list-title">片名</a></li>';const {c}=ctx(()=>html('<html><div><div><h2>最近更新</h2></div>'+a+a+'</div><div><h2>热门推荐</h2>'+a.replace('1.html','2.html')+'</div></html>'));assert.equal((await c.loadHome()).length,2);const r=await c.loadLatest();assert.equal(r.length,1);assert.equal(r[0].coverUrl,'https://img.test/a.jpg');});
await test('195 complete episodes, correct matching source names and independent detail objects',async()=>{const {c}=ctx(()=>html(fixture()));const d=await c.loadDetail(detailLink);assert.equal(d.episodeItems.length,195);assert.equal(d.episodeItems[100].title,'第101集');assert.equal(d.episodeItems[194].link,site+'/bovideo/1-1-194.html');assert.equal(d.episodeItems[0].childItems[0].title,'秒播 · 第1集');});
await test('bad identity, missing episodes, duplicates and badge mismatch never yield partial detail',async()=>{for(const s of [fixture(2).replace('bovod/1','bovod/2'),fixture(2).replace('-1-1.html','-1-3.html'),fixture(2).replace('-1-1.html','-1-0.html'),fixture(2).replace('2集</sup>','195集</sup>')]){const {c}=ctx(()=>html(s));await assert.rejects(c.loadDetail(detailLink));}});
await test('player data only accepts literal strings bound to selected movie, line and episode',()=>{const {c}=ctx(()=>html('')),ids=c.ebParse(epLink);assert.equal(c.ebPlayer(player('https://media.test/a.m3u8'),ids),'https://media.test/a.m3u8');for(const s of [player('https://media.test/a.m3u8','2'),player('https://media.test/a.m3u8','1','2'),player('https://media.test/a.m3u8','1','1','1'),'<script>var now=evil()</script>'])assert.throws(()=>c.ebPlayer(s,ids));});
await test('HLS highest child fixed while audio group retained',async()=>{for(const audio of [false,true]){const {c}=ctx((m,u)=>html(u.endsWith('/a.m3u8')?'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1,RESOLUTION=1920x1080'+(audio?',AUDIO="a"':'')+'\nb.m3u8':'#EXTM3U\n#EXTINF:4,\ns.ts'));const r=await c.ebHls('https://media.test/a.m3u8',{},'fixed',{reads:0,maxReads:6});assert.equal(r.url,'https://media.test/'+(audio?'a':'b')+'.m3u8');}});
await test('inflight playback merged and future requests freshly read',async()=>{const {c,requests}=ctx((m,u)=>html(u===detailLink?fixture(1):u===epLink?player('https://media.test/a.m3u8'):'#EXTM3U\n#EXTINF:4,\ns.ts'));const [a,b]=await Promise.all([c.loadResource({link:epLink}),c.loadResource({link:epLink})]);assert.equal(a[0].url,b[0].url);assert.equal(requests.length,3);await c.loadResource({link:epLink});assert.equal(requests.length,6);});
await test('HTTP errors and TLS give explicit failure and rate limit is not retried',async()=>{for(const status of [403,429,502]){const {c,requests}=ctx(()=>({statusCode:status,data:''}));await assert.rejects(c.loadHome());assert.equal(requests.length,1);}const {c}=ctx(()=>{throw new Error('TLS connection failed');});await assert.rejects(c.loadHome(),/HTTPS连接失败/);});
await test('MP4 HEAD rejects HTML without downloading video',async()=>{for(const ct of ['video/mp4','text/html']){const {c,requests}=ctx(()=>({statusCode:200,headers:{'content-type':ct}}));if(ct==='video/mp4')await c.ebMp4('https://media.test/a.mp4');else await assert.rejects(c.ebMp4('https://media.test/a.mp4'));assert.equal(requests[0].m,'HEAD');}});
await test('original VIP signer receives exact source and refuses a different media path',async()=>{for(const path of ['a','b']){const {c,requests}=ctx(()=>html("<html><script>var url = 'https://media.test/"+path+".m3u8?sign=test';</script></html>"));if(path==='a')assert.equal(await c.ebSigned('https://media.test/a.m3u8','vip','/bovideo/1-1-0.html'),'https://media.test/a.m3u8?sign=test');else await assert.rejects(c.ebSigned('https://media.test/a.m3u8','vip','/bovideo/1-1-0.html'));assert.equal(requests[0].u,'https://tv.qingning88.com/api/publicApi.php?url=https://media.test/a.m3u8&code=vip');assert.equal(requests[0].o.headers.Referer,epLink);}});
await test('VIP normal issuance checked as HLS and signer Referer carried into playback',async()=>{const {c,requests}=ctx((m,u)=>html(u===detailLink?fixture(1):u===epLink?player('https://media.test/a.m3u8').replace('</script>','var pn="vip";</script>'):u.startsWith('https://tv.qingning88.com/')?"<html><script>var url = 'https://media.test/a.m3u8?sign=test';</script></html>":'#EXTM3U\n#EXTINF:4,\ns.ts'));const out=await c.loadResource({link:epLink});assert.equal(out[0].url,'https://media.test/a.m3u8?sign=test');assert.equal(out[0].customHeaders.Referer,'https://tv.qingning88.com/');assert.equal(requests.length,4);});
console.log(passed+' Eboyang tests passed');})().catch(e=>{console.error(e);process.exitCode=1;});
