const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');let passed=0;
const code=fs.readFileSync(__dirname+'/zip0.js','utf8'),media='#EXTM3U\n#EXTINF:6,\nseg.ts';
const detail=count=>({id:'8298',source:'dyttzy',sourceName:'线路 1',title:'凡人修仙传',poster:'https://poster.test/a.jpg',year:'2020',remarks:'更新至195集',category:'国产动漫',episodeCount:count,description:'简介',episodes:Array.from({length:count},(_,i)=>({name:'第'+(i+1)+'集',url:'https://media.test/'+(i+1)+'.m3u8'}))});
function literal(v){if(Array.isArray(v))return '['+v.map(literal).join(',')+']';if(v&&typeof v==='object')return '{'+Object.entries(v).map(([k,v])=>k+':'+literal(v)).join(',')+'}';return JSON.stringify(v);}
function html(d){return '<script>ignored(); x={l:$R[15]='+literal(d)+'};</script>';}
function setup(){const calls=[],c=vm.createContext({Widget:{http:{get:async u=>{calls.push(u);return {statusCode:200,data:u.includes('/watch?')?html(detail(195)):media};}}}});vm.runInContext(code,c);return {c,calls};}
async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
(async()=>{
 await test('independent module identity, exact six website categories and uncached streams',()=>{const {c}=setup();assert.equal(c.WidgetMetadata.id,'joeshu.zip0');assert.equal(c.WidgetMetadata.site,'https://zip0.com');assert.equal(c.ZipCategories.length,6);assert.equal(c.WidgetMetadata.modules.find(x=>x.type==='stream').cacheDuration,0);});
 await test('SSR literal assignments, shared references, escaped strings and boolean encodings',()=>{const {c}=setup();const d=c.zipLiteral('{a:$R[1]={title:"中\\\"文",n:!0,x:void 0},b:$R[1],v:!1}');assert.equal(d.a,d.b);assert.equal(d.a.title,'中"文');assert.equal(d.a.n,true);assert.equal(d.v,false);assert.equal(d.a.x,null);});
 await test('SSR parser rejects calls, operators, unknown refs and prototype keys',()=>{const {c}=setup();for(const s of ['{a:evil()}','{a:(1+2)}','{a:$R[7]}','{__proto__:{x:1}}','{constructor:1}','{a:new Date()}'])assert.throws(()=>c.zipLiteral(s),/格式/);assert.equal(c.polluted,undefined);});
 await test('parser bounds nesting and body size',()=>{const {c}=setup();assert.throws(()=>c.zipLiteral('['.repeat(40)+'0'+']'.repeat(40)),/格式/);assert.throws(()=>c.zipLoader(' '.repeat(c.ZIP0.maxBody+1),'detail'),/格式/);});
 await test('empty searches are idle and keyword/page validation precedes network',async()=>{const {c,calls}=setup();assert.equal((await c.search({keyword:' \u200b '})).length,0);await assert.rejects(c.search({keyword:'x'.repeat(61)}),/60/);await assert.rejects(c.search({keyword:'test',page:-1}),/页码/);assert.equal(calls.length,0);});
 await test('public search keeps source identity, same-title versions and pagination',async()=>{const {c,calls}=setup();c.Widget.http.get=async u=>{calls.push(u);return {statusCode:200,data:{success:true,pagination:{page:2},data:[{title:'同名',year:'2020',category:'国产动漫',url:'https://zip0.com/watch?source=dyttzy&id=1&episode=1'},{title:'同名',year:'2025',category:'国产剧',url:'https://zip0.com/watch?source=ikun&id=2&episode=1'}]}};};const r=await c.search({keyword:'同名',page:2});assert.equal(r.length,2);assert.notEqual(r[0].id,r[1].id);assert(calls[0].includes('page=2&limit=20'));assert.equal(r[1].releaseDate,'2025');});
 await test('search rejects mismatched server pagination',async()=>{const {c}=setup();c.Widget.http.get=async()=>({statusCode:200,data:{success:true,pagination:{page:1},data:[]}});await assert.rejects(c.search({keyword:'a',page:2}),/页码不一致/);});
 await test('catalog parses rich SSR data and preserves source cards without truncation',async()=>{const {c,calls}=setup();const cards=Array.from({length:74},(_,i)=>({...detail(1),id:String(i+1)}));c.Widget.http.get=async u=>{calls.push(u);return {statusCode:200,data:html({initialResponse:{items:cards,hasMore:true}})};};const r=await c.loadCatalog({category:'sports',page:2});assert.equal(r.length,74);assert(calls[0].endsWith('/category/sports?page=2'));assert.equal(r[0].coverUrl,'https://poster.test/a.jpg');await assert.rejects(c.loadCatalog({category:'fake'}),/分类/);});
 await test('all failed upstream sources do not masquerade as empty search or catalog',async()=>{const {c}=setup();c.Widget.http.get=async()=>({statusCode:200,data:html({initialResponse:{items:[],sourceHealth:[{status:'error'},{status:'timeout'}]}})});await assert.rejects(c.loadCatalog({}),/来源暂不可用/);c.Widget.http.get=async()=>({statusCode:200,data:{success:true,data:[],pagination:{page:1},sources:{total:10,completed:0}}});await assert.rejects(c.search({keyword:'a'}),/来源暂不可用/);});
 await test('detail exposes episodes 101 and 195 with native site ordinal links',async()=>{const {c}=setup();const r=await c.loadDetail('https://zip0.com/watch?source=dyttzy&id=8298&episode=1');assert.equal(r.episodeItems.length,195);assert.equal(r.episodeItems[100].title,'第101集');assert(r.episodeItems[194].link.endsWith('episode=195'));assert(r.description.includes('195 个分集条目'));});
 await test('count mismatch never returns a truncated detail',async()=>{const {c}=setup();c.Widget.http.get=async()=>({statusCode:200,data:html({...detail(100),episodeCount:195})});await assert.rejects(c.loadDetail('https://zip0.com/watch?source=dyttzy&id=8298&episode=1'),/不完整/);});
 await test('wrong source or ID is rejected',async()=>{const {c}=setup();for(const link of ['https://zip0.com/watch?source=ikun&id=8298&episode=1','https://zip0.com/watch?source=dyttzy&id=1&episode=1'])await assert.rejects(c.loadDetail(link),/不匹配/);});
 await test('resource selects requested episode 101 and refreshes detail for each call',async()=>{const {c,calls}=setup(),link='https://zip0.com/watch?source=dyttzy&id=8298&episode=101';let r=await c.loadResource({link});assert.equal(r[0].url,'https://media.test/101.m3u8');assert(r[0].name.includes('第101集'));await c.loadResource({link});assert.equal(calls.filter(u=>u.includes('/watch?')).length,2);});
 await test('out-of-range episode, foreign link and invalid preference fail explicitly',async()=>{const {c}=setup();await assert.rejects(c.loadResource({link:'https://zip0.com/watch?source=dyttzy&id=8298&episode=196'}),/不存在/);assert.throws(()=>c.zipParse('https://evil.test/watch?source=dyttzy&id=8298'),/ZIP0/);await assert.rejects(c.loadResource({qualityPreference:'fake'}),/画质/);});
 await test('HLS highest selection, fixed option and relative URI resolution',async()=>{const {c}=setup();c.Widget.http.get=async u=>({statusCode:200,data:u.endsWith('master.m3u8')?'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1,RESOLUTION=640x360\nlow.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=2,RESOLUTION=1920x1080\n../high.m3u8':media});const r=await c.zipHls('https://media.test/p/master.m3u8',{},'fixed');assert.equal(r.url,'https://media.test/high.m3u8');assert.equal(r.height,1080);assert(r.fixed);assert.equal((await c.zipHls('https://media.test/p/master.m3u8',{},'highest')).url,'https://media.test/p/master.m3u8');});
 await test('independent audio/subtitles retain master and reject detached fallbacks',async()=>{const {c}=setup();let fail=false;c.Widget.http.get=async u=>({statusCode:fail&&u.endsWith('high.m3u8')?403:200,data:u.endsWith('master.m3u8')?'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=2,AUDIO="a",SUBTITLES="s"\nhigh.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=1,AUDIO="a"\nlow.m3u8':media});const r=await c.zipHls('https://media.test/master.m3u8',{},'fixed');assert.equal(r.url,'https://media.test/master.m3u8');assert(!r.fixed);assert(r.retained);fail=true;await assert.rejects(c.zipHls('https://media.test/master.m3u8',{},'fixed'),/独立音轨/);});
 await test('HTML, empty HLS, recursive manifests and non-HTTP URLs are rejected',async()=>{const {c,calls}=setup();for(const data of ['<html>bad</html>','#EXTM3U']){c.Widget.http.get=async()=>({statusCode:200,data});await assert.rejects(c.zipHls('https://media.test/a.m3u8',{},'fixed'));}let count=0;c.Widget.http.get=async()=>{count++;return {statusCode:200,data:'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1\nnext.m3u8'};};await assert.rejects(c.zipHls('https://media.test/a.m3u8',{},'fixed'));assert(count<=5);for(const u of ['javascript:alert(1)','https://user:pass@host/a','file:///a'])assert.throws(()=>c.zipUrl(u));});
 await test('429 immediately stops additional HLS variants and API calls',async()=>{const {c}=setup();let count=0;c.Widget.http.get=async()=>{count++;return {statusCode:429,data:'limited'};};await assert.rejects(c.zipHls('https://media.test/a.m3u8',{},'fixed'),e=>e.code==='RATE_LIMIT');assert.equal(count,1);await assert.rejects(c.search({keyword:'a'}),e=>e.code==='RATE_LIMIT');});
 await test('MP4 is returned without downloading video; web wrappers fail explicitly',async()=>{const {c,calls}=setup();let url='https://media.test/a.mp4';c.Widget.http.get=async u=>{calls.push(u);const d=detail(1);d.episodes[0].url=url;return {statusCode:200,data:html(d)};};const link='https://zip0.com/watch?source=dyttzy&id=8298&episode=1';assert.equal((await c.loadResource({link}))[0].url,url);assert.equal(calls.length,1);url='https://media.test/player?url=secret';await assert.rejects(c.loadResource({link}),/网页播放器/);});
 console.log(passed+' ZIP0 tests passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
