const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(__dirname+'/auete.js','utf8'),site='https://www.au1080.top',root='/Dm/guoman/test/';
function detail(n=195,two=true){let lines='';for(let l=0;l<(two?2:1);l++){let a='';for(let i=0;i<n;i++)a+=`<li><a href="${root}play-${l}-${i}.html">第${i+1}集</a></li>`;lines+=`<div class="play-card"><div class="card-header"><b>线路${l}</b></div><ul class="episode-list">${a}</ul></div>`;}return '<html><h1 class="detail-title">《测试》</h1><div class="detail-poster"><img src="/cover.jpg"></div><span class="badge-time">2020</span><div class="detail-status-item"><b class="value">至'+n+'集/共888集</b></div><p class="detail-des">剧情</p>'+lines+'</html>';}
const media='#EXTM3U\n#EXTINF:5,\nsegment.ts\n';const play=u=>'<html><script>var now=base64decode("'+Buffer.from(u).toString('base64')+'");</script></html>';
(async()=>{const {WidgetAdaptor}=await import('./node_modules/@rexnow/libs/dist/widget-adaptor.js');let passed=0;
function ctx(handler){const requests=[];const c=vm.createContext({Widget:{html:WidgetAdaptor.html,http:{get:async(u,o)=>{requests.push({u,o});return handler?handler(u,o):{statusCode:200,data:detail()};}}}});vm.runInContext(source,c);return {c,requests};}
async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
await test('immutable snapshot equals standalone source',()=>assert.equal(fs.readFileSync(__dirname+'/auete-0.1.0.js','utf8'),source));
await test('only published origins and strict detail/episode paths accepted',()=>{const {c}=ctx();for(const u of ['https://evil.test'+root,site+root+'?x=1',site+'/Movie/../x/',site+'@evil.test'+root])assert.throws(()=>c.auParse(u));assert.equal(c.auParse(site+root+'play-1-100.html').index,100);});
await test('real category pagination and invalid categories',async()=>{const {c,requests}=ctx(()=>({statusCode:200,data:'<html></html>'}));await c.loadCatalog({category:'Tv',page:2});assert.equal(requests[0].u,site+'/Tv/index2.html');await c.loadCatalog({category:'Movie',page:1});assert.equal(requests[1].u,site+'/Movie/index.html');await assert.rejects(c.loadCatalog({category:'fake'}));await assert.rejects(c.loadCatalog({page:0}));});
await test('recent updates and realtime hot use separate original endpoints',async()=>{const {c,requests}=ctx(()=>({statusCode:200,data:'<html></html>'}));await c.loadLatest();await c.loadLatest({list:'hot'});assert.equal(requests[0].u,site+'/daynew.php');assert.equal(requests[1].u,site+'/dayhot.php');});
await test('search encodes keyword and explicit captcha failure is not an empty result',async()=>{const {c,requests}=ctx(()=>({statusCode:200,data:'<title>系统安全验证</title><input name="vdcode">'}));await assert.rejects(c.search({keyword:'a&b'}),/验证码/);assert.equal(requests[0].u,site+'/auete4so.php?searchword=a%26b');assert.equal((await c.search({keyword:'x',page:2})).length,0);});
await test('HTTP errors, HTML challenge and 429 are explicit and not retried',async()=>{for(const status of [403,502,429]){const {c,requests}=ctx(()=>({statusCode:status,data:'<html></html>'}));await assert.rejects(c.loadHome());assert.equal(requests.length,1);}});
await test('cards deduplicate and parse images/rating/update without false release year',async()=>{const {c}=ctx();const card='<li data-href="/Movie/xjp/test/"><a class="pic"><img src="/a.jpg" alt="片名"><span class="rating">7.4分</span><span class="hdtag">HD中字</span></a><h2><a>片名</a></h2><span class="update-time">2026-10-09</span></li>';const a=await c.auCards('<ul class="threadlist">'+card+card+'</ul>',site);assert.equal(a.length,1);assert.equal(a[0].rating,'7.4');assert.equal(a[0].mediaType,'movie');assert.equal(a[0].coverUrl,site+'/a.jpg');assert.equal(a[0].releaseDate,undefined);});
await test('195 episodes include 101 and 195 and same-episode line alternatives',async()=>{const {c}=ctx();const d=await c.loadDetail(site+root);assert.equal(d.episodeItems.length,195);assert.equal(d.episodeItems[100].title,'第101集');assert.equal(d.episodeItems[194].childItems.length,2);assert.equal(d.episodeItems[194].childItems[1].link,site+root+'play-1-194.html');assert.equal(d.releaseDate,'2020');assert(d.description.includes('剧情'));});
await test('duplicate, wrong-title path and missing episode are rejected',async()=>{for(const t of [detail(2).replace('play-0-1','play-0-0'),detail(3,false).replace(/<li><a href="[^\"]+play-0-1.html">.*?<\/li>/,''),detail(2).replace('play-0-0.html','../bad/')]){const {c}=ctx(()=>({statusCode:200,data:t}));await assert.rejects(c.loadDetail(site+root));}});
await test('advertised update count missing from all lines fails instead of truncation',async()=>{const {c}=ctx(()=>({statusCode:200,data:detail(100).replace('至100集','至195集')}));await assert.rejects(c.loadDetail(site+root),/不完整/);});
await test('longest line is selected without generating nonexistent episodes on shorter line',async()=>{const t=detail(3,false)+detail(2,false).replaceAll('play-0-','play-1-');const {c}=ctx(()=>({statusCode:200,data:t}));const d=await c.loadDetail(site+root);assert.equal(d.episodeItems.length,3);assert.equal(d.episodeItems[2].childItems.length,1);});
await test('detail in-flight merge expires before next refresh',async()=>{const {c,requests}=ctx();await Promise.all([c.loadDetail(site+root),c.loadDetail(site+root)]);assert.equal(requests.length,1);await c.loadDetail(site+root);assert.equal(requests.length,2);});
await test('base64 decoded without atob/browser globals and unsafe URLs rejected',()=>{const {c}=ctx();const u='https://media.test/a.m3u8?x=1';assert.equal(c.auBase64(Buffer.from(u).toString('base64')),u);for(const s of ['@@@@',Buffer.from('javascript:alert(1)').toString('base64')])assert.throws(()=>c.auBase64(s));});
await test('failed selected line falls back only to same episode',async()=>{const {c,requests}=ctx(u=>({statusCode:200,data:u===site+root?detail(2):u.endsWith('play-0-1.html')?'<html>unsupported</html>':u.endsWith('play-1-1.html')?play('https://media.test/a.m3u8'):media}));const r=await c.loadResource({link:site+root+'play-0-1.html'});assert.equal(r.length,1);assert(r[0].name.includes('第2集'));assert(!requests.some(x=>/play-\d-0.html/.test(x.u)));});
await test('success retained when later line fails; MP4 remains actual URL',async()=>{const {c}=ctx(u=>({statusCode:200,data:u===site+root?detail(1):u.endsWith('play-0-0.html')?play('https://media.test/a.mp4'):'<html>unsupported</html>'}));const r=await c.loadResource({link:site+root+'play-0-0.html'});assert.equal(r[0].url,'https://media.test/a.mp4');});
await test('429 stops fallback immediately',async()=>{const {c,requests}=ctx(u=>u===site+root?{statusCode:200,data:detail(2)}:{statusCode:429,data:''});await assert.rejects(c.loadResource({link:site+root+'play-0-0.html'}),/频繁/);assert.equal(requests.length,2);});
await test('master fixed mode selects high resolution; external audio stays attached',async()=>{for(const external of [false,true]){const m='#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1,RESOLUTION=1920x1080'+(external?',AUDIO="a"':'')+'\nhi.m3u8\n';const {c}=ctx(u=>({statusCode:200,data:u.endsWith('master.m3u8')?m:media}));const r=await c.auHls('https://media.test/master.m3u8',{},'fixed');assert.equal(r.url,'https://media.test/'+(external?'master':'hi')+'.m3u8');}});
await test('empty/HTML/cyclic HLS is bounded',async()=>{for(const body of ['<html></html>','#EXTM3U\n','#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1\nmaster.m3u8\n']){const {c,requests}=ctx(()=>({statusCode:200,data:body}));await assert.rejects(c.auHls('https://media.test/master.m3u8',{},'highest',{reads:0,maxReads:6}));assert(requests.length<=5);}});
console.log(`${passed} Auete tests passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
