const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const source=fs.readFileSync(__dirname+'/4kvm.js','utf8');
const site='https://www.4kvms.org';
function page(count=195,options={}){
 const n=options.actual??count;const lines=options.two?`{lineName:'alists',episodeCount:${count}},{lineName:'backup',episodeCount:${count}}`:`{lineName:'alists',episodeCount:${count}}`;
 let anchors='';for(let l=1;l<=(options.two?2:1);l++)for(let e=1;e<=n;e++)anchors+=`<a href="/play/${l===1?'ep':'other'}${e}" data-line="${l}" data-episode="${e}" dataid="${1000*l+e}">${e}</a>`;
 return `<!DOCTYPE html><html><head><meta id="nb-st" content="1750000000000"><meta property="og:image" content="https://images.test.org/cover.jpg"><meta name="description" content="Test plot"><link id="wasm-cfg" data-bg="${options.changed?'/static/wasm/new.wasm':'/static/wasm/nbmovie_wasm_bg.d5d51939.wasm'}"></head><body><h1>测试剧</h1><div x-data="{userlink:'0'}"></div><div x-data="episodeManager(1,1,[${lines}])">${anchors}</div></body></html>`;
}
(async()=>{
 const {WidgetAdaptor}=await import('./node_modules/@rexnow/libs/dist/widget-adaptor.js');let passed=0;
 function context(handler){const requests=[],ctx=vm.createContext({WebAssembly:undefined,TextEncoder:undefined,TextDecoder:undefined,window:undefined,document:undefined,Widget:{html:WidgetAdaptor.html,http:{get:async(url,options)=>{requests.push({url,options});return handler?handler(url,options):{statusCode:200,data:page()};}}}});vm.runInContext(source,ctx);return {ctx,requests};}
 async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
 const plain=x=>JSON.parse(JSON.stringify(x));
 await test('assembled standalone source matches its three source parts',()=>{assert.equal(source,['4kvm-adapter.js','4kvm-hls.js','4kvm-player.js'].map(p=>fs.readFileSync(__dirname+'/'+p,'utf8')).join('\n'));});
 await test('private pure JS compiler matches original WASM fixed-time golden with no browser globals',()=>{const {ctx}=context();const f=ctx.vm4Build({st:'1750000000000',plt:'1750000000123'},1750000000123);assert.equal(crypto.createHash('sha256').update(f('1551','cgzq7f3tf','1080','0')).digest('hex'),'6a0db81666ecd0bd073bdb40501ebfc28c0a5495ca690966afd521ff59d70804');assert.equal(ctx.WebAssembly,undefined);assert.equal(ctx.window,undefined);});
 await test('private codec rejects non-ASCII parameters and malformed page timestamps',()=>{const {ctx}=context();assert.throws(()=>ctx.vm4Build({st:'bad',plt:'1750000000123'},1750000000123));const f=ctx.vm4Build({st:'1750000000000',plt:'1750000000123'},1750000000123);assert.throws(()=>f('1551','中文','1080','0'),/ASCII/);});
 await test('only published preset origins and actual page keys are accepted',()=>{const {ctx}=context();for(const u of ['https://evil.test/play/ep1',site+'/play/ep1?x=1',site+'/play/../secret',site+'@evil.test/play/ep1'])assert.throws(()=>ctx.vm4Parse(u));assert.equal(ctx.vm4Parse(site+'/play/ep101').key,'ep101');});
 await test('category uses real filter pagination and sorting rather than landing-page pseudo-pagination',async()=>{const {ctx,requests}=context(()=>({statusCode:200,data:'<!doctype html><html></html>'}));await ctx.loadCatalog({category:'3',sort:'score',page:2});assert.equal(requests[0].url,site+'/filter?classify=3&sort_by=score&order=desc&page=2');await assert.rejects(ctx.loadCatalog({category:'999'}));await assert.rejects(ctx.loadCatalog({page:-1}));});
 await test('search encodes keywords and stops at the original single page without repeating results',async()=>{const {ctx,requests}=context(()=>({statusCode:200,data:'<!doctype html><html></html>'}));await ctx.search({keyword:'a&b',page:1});assert.equal(requests[0].url,site+'/search?q=a%26b');assert.deepEqual(plain(await ctx.search({keyword:'a&b',page:2})),[]);assert.equal(requests.length,1);assert.deepEqual(plain(await ctx.search({keyword:' '})),[]);});
 await test('cards decode image entities, deduplicate page keys and use real posters',async()=>{const {ctx}=context();const card='<a data-vod="id1" href="/play/ep1"><img data-src="https://images.test.org/c.jpg?a=1&amp;b=2" alt="测试"><h3>测试</h3><span>2020</span></a>';const items=await ctx.vm4Cards('<html>'+card+card+'</html>',site,'1');assert.equal(items.length,1);assert.equal(items[0].coverUrl,'https://images.test.org/c.jpg?a=1&b=2');assert.equal(items[0].mediaType,'movie');assert.equal(items[0].releaseDate,'2020');});
 await test('complete detail includes 101 and 195 with actual distinct episode addresses',async()=>{const {ctx}=context();const d=await ctx.loadDetail(site+'/play/ep1');assert.equal(d.episodeItems.length,195);assert.equal(d.episodeItems[100].link,site+'/play/ep101');assert.equal(d.episodeItems[194].title,'第195集');});
 await test('declared count mismatch fails instead of silently returning 100 of 195',async()=>{const {ctx}=context(()=>({statusCode:200,data:page(195,{actual:100})}));await assert.rejects(ctx.loadDetail(site+'/play/ep1'),/不完整/);});
 await test('same-episode alternatives retain each actual line page key',async()=>{const {ctx}=context(()=>({statusCode:200,data:page(2,{two:true})}));const d=await ctx.loadDetail(site+'/play/ep1');assert.equal(d.episodeItems[1].childItems.length,2);assert.equal(d.episodeItems[1].childItems[1].link,site+'/play/other2');});
 await test('wrong detail or duplicate episode address fails closed',async()=>{const {ctx}=context();await assert.rejects(ctx.loadDetail(site+'/play/missing'),/不匹配/);const p=page(2).replace('/play/ep2','/play/ep1');await assert.rejects(ctx.vm4DecodePage(p,ctx.vm4Parse(site+'/play/ep1')),/重复/);});
 await test('concurrent reads merge only in flight and next detail refreshes',async()=>{const {ctx,requests}=context();await Promise.all([ctx.loadDetail(site+'/play/ep1'),ctx.loadDetail(site+'/play/ep1')]);assert.equal(requests.length,1);await ctx.loadDetail(site+'/play/ep1');assert.equal(requests.length,2);});
 await test('new upstream WASM version requires module update before requesting playback',async()=>{const {ctx,requests}=context(()=>({statusCode:200,data:page(2,{changed:true})}));await assert.rejects(ctx.loadResource({link:site+'/play/ep1'}),/播放器已更新/);assert.equal(requests.length,1);});
 await test('guest permission flags must explicitly indicate unlocked non-member access',()=>{const {ctx}=context();for(const x of [{locked:true,isvip:false},{locked:false,isvip:'true'},{locked:'TRUE',isvip:false},{isvip:false},{locked:false}])assert.equal(ctx.vm4Allowed({...x,url:'https://media.test/video.m3u8'}),false);assert.equal(ctx.vm4Allowed({locked:false,isvip:false,url:'https://media.test/video.m3u8'}),true);});
 await test('playback filters locked 4K and uses fresh metadata without leaking page token in headers',async()=>{const q=[{title:'4K',locked:true,isvip:true,url:'https://media.test/locked.m3u8',mtype:'m3u8',bitrate:2160000},{title:'1080p',locked:false,isvip:false,url:'https://media.test/open.m3u8',mtype:'m3u8',bitrate:1080}];const {ctx,requests}=context(url=>url.includes('/video/play?')?{statusCode:200,data:{code:200,data:{quality_urls:q}}}:url.includes('media.test')?{statusCode:200,data:'#EXTM3U\n#EXTINF:5,\nsegment.ts\n'}:{statusCode:200,data:page(2)});const r=await ctx.loadResource({link:site+'/play/ep2'});assert.equal(r.length,1);assert(r[0].name.includes('1080p'));assert(!requests.some(x=>x.url.includes('locked.m3u8')));assert.equal(r[0].customHeaders.Referer,undefined);assert(requests.some(x=>x.url.startsWith(site+'/video/play?p=')));});
 await test('all locked resources produce explicit permission failure',async()=>{const {ctx}=context(url=>url.includes('/video/play?')?{statusCode:200,data:{code:200,data:{quality_urls:[{locked:true,isvip:true,url:'https://media.test/a.m3u8'}]}}}:{statusCode:200,data:page(1)});await assert.rejects(ctx.loadResource({link:site+'/play/ep1'}),/没有游客可用/);});
 await test('HTML error bodies and 429 are not treated as valid data or retried',async()=>{const {ctx,requests}=context(()=>({statusCode:429,data:'<html>limited</html>'}));await assert.rejects(ctx.loadHome(),/过于频繁/);assert.equal(requests.length,1);const {ctx:c}=context(()=>({statusCode:200,data:'<html><title>Site Unavailable</title></html>'}));await assert.rejects(c.loadHome(),/未返回影片页面/);});
 await test('HLS master fixed mode chooses declared high-resolution child',async()=>{const master='#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=100000,RESOLUTION=640x360\nlo.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=200000,RESOLUTION=1920x1080\nhi.m3u8\n';const {ctx}=context(u=>({statusCode:200,data:u.endsWith('/master.m3u8')?master:'#EXTM3U\n#EXTINF:3,\ns.ts\n'}));const r=await ctx.vm4Hls('https://media.test/master.m3u8',{},'fixed');assert.equal(r.url,'https://media.test/hi.m3u8');assert.equal(r.height,1080);assert.equal(r.fixed,true);});
 await test('HLS external audio remains attached to master in fixed mode',async()=>{const master='#EXTM3U\n#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="a",URI="audio.m3u8"\n#EXT-X-STREAM-INF:BANDWIDTH=200000,RESOLUTION=1920x1080,AUDIO="a"\nhi.m3u8\n';const {ctx}=context(u=>({statusCode:200,data:u.endsWith('/master.m3u8')?master:'#EXTM3U\n#EXTINF:3,\ns.ts\n'}));const r=await ctx.vm4Hls('https://media.test/master.m3u8',{},'fixed');assert.equal(r.url,'https://media.test/master.m3u8');assert.equal(r.fixed,false);});
 await test('empty, HTML and cyclic HLS fail with bounded requests',async()=>{for(const body of ['<html>error</html>','#EXTM3U\n','#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1\nmaster.m3u8\n']){const {ctx,requests}=context(()=>({statusCode:200,data:body}));await assert.rejects(ctx.vm4Hls('https://media.test/master.m3u8',{},'highest'));assert(requests.length<=5);}});

 await test('filters resolve real year/area/type IDs from site and cache public taxonomy only',async()=>{const {ctx,requests}=context(url=>({statusCode:200,data:url===site+'/filter'?'<html><a href="?areas=5">美国</a><a href="?types=14">科幻</a><a href="?years=91">2026</a></html>':'<!doctype html><html></html>'}));await ctx.loadCatalog({category:'1',area:'美国',genre:'科幻',year:'2026',page:2});assert.equal(requests[1].url,site+'/filter?classify=1&areas=5&types=14&years=91&sort_by=update_time&order=desc&page=2');await ctx.loadCatalog({year:'2026'});assert.equal(requests.filter(x=>x.url===site+'/filter').length,1);assert.equal(ctx.vm4FacetCache[site].maps.years['2026'],'91');});
 await test('unknown filter names or malformed year never generate guessed IDs',async()=>{const {ctx,requests}=context(()=>({statusCode:200,data:'<html><a href="?years=91">2026</a></html>'}));await assert.rejects(ctx.loadCatalog({year:'2026&areas=5'}),/无效/);assert.equal(requests.length,0);await assert.rejects(ctx.loadCatalog({area:'不存在'}),/未提供/);assert.equal(requests.length,1);});
 await test('taxonomy expires and recent-update module always uses update ordering',async()=>{const {ctx,requests}=context(url=>({statusCode:200,data:url===site+'/filter'?'<html><a href="?years=91">2026</a></html>':'<!doctype html><html></html>'}));await ctx.loadLatest({sort:'score',year:'2026'});assert(requests[1].url.includes('sort_by=update_time'));ctx.vm4FacetCache[site].time-=600001;await ctx.loadCatalog({year:'2026'});assert.equal(requests.filter(x=>x.url===site+'/filter').length,2);});
 await test('card metadata comes from full card, includes episode update and avoids inventing movie type',async()=>{const {ctx}=context();const card='<div class="movie-card"><a data-vod="id" href="/play/ep1"><img data-src="https://images.test.org/poster.jpg" alt="动画"><span>更新至195集</span></a><span class="font-bold">9.2</span><span>2020</span><span>4k</span><p>剧情</p><a class="aspect-video"><img data-src="https://images.test.org/backdrop.jpg"></a></div>';const items=await ctx.vm4Cards(card,site);assert.equal(items[0].releaseDate,'2020');assert.equal(items[0].rating,'9.2');assert(items[0].description.includes('更新至195集'));assert(items[0].description.includes('游客可用画质'));assert.equal(items[0].backdropPath,'https://images.test.org/backdrop.jpg');assert.equal(items[0].mediaType,undefined);});
 function playContext(qualities,media){return context(url=>url.includes('/video/play?')?{statusCode:200,data:{code:200,data:{quality_urls:qualities}}}:url.startsWith('https://media.test/')?media(url):{statusCode:200,data:page(2)});}
 function quality(title,url,bitrate){return {title,url,bitrate,mtype:'m3u8',locked:false,isvip:false};}
 await test('failed higher quality falls back to unlocked same-episode lower quality',async()=>{const {ctx}=playContext([quality('1080p','https://media.test/bad.m3u8',1080),quality('720p','https://media.test/good.m3u8',720)],url=>({statusCode:url.includes('/bad.')?502:200,data:'#EXTM3U\n#EXTINF:5,\ns.ts\n'}));const r=await ctx.loadResource({link:site+'/play/ep2'});assert.equal(r.length,1);assert(r[0].name.includes('720p'));assert(r[0].name.includes('第2集'));});
 await test('failed later quality does not discard already validated higher quality',async()=>{const {ctx}=playContext([quality('720p','https://media.test/bad.m3u8',9000000),quality('1080p','https://media.test/good.m3u8',1080)],url=>({statusCode:200,data:url.includes('/bad.')?'<html>error</html>':'#EXTM3U\n#EXTINF:5,\ns.ts\n'}));const r=await ctx.loadResource({link:site+'/play/ep1'});assert.equal(r.length,1);assert(r[0].name.includes('1080p'));});
 await test('duplicate qualities and concurrent playback share requests only while in flight',async()=>{const q=quality('1080p','https://media.test/good.m3u8',1080);const {ctx,requests}=playContext([q,q],()=>({statusCode:200,data:'#EXTM3U\n#EXTINF:5,\ns.ts\n'}));const r=await Promise.all([ctx.loadResource({link:site+'/play/ep1'}),ctx.loadResource({link:site+'/play/ep1'})]);assert.equal(r[0].length,1);assert.equal(requests.filter(x=>x.url.includes('/video/play?')).length,1);assert.equal(requests.filter(x=>x.url.includes('media.test')).length,1);await ctx.loadResource({link:site+'/play/ep1'});assert.equal(requests.filter(x=>x.url.includes('/video/play?')).length,2);});
 await test('HLS total budget applies across qualities and rate limit stops all fallback',async()=>{const {ctx,requests}=context(()=>({statusCode:200,data:'#EXTM3U\n#EXTINF:5,\ns.ts\n'}));const budget={reads:0,maxReads:2};await ctx.vm4Hls('https://media.test/a.m3u8',{},'highest',budget);await ctx.vm4Hls('https://media.test/b.m3u8',{},'highest',budget);await assert.rejects(ctx.vm4Hls('https://media.test/c.m3u8',{},'highest',budget),/总请求上限/);assert.equal(requests.length,2);const {ctx:c,requests:rs}=playContext([quality('1080p','https://media.test/limited.m3u8',1080),quality('720p','https://media.test/good.m3u8',720)],()=>({statusCode:429,data:''}));await assert.rejects(c.loadResource({link:site+'/play/ep1'}),/过于频繁/);assert.equal(rs.filter(x=>x.url.includes('media.test')).length,1);});
 console.log(passed+' 4K影视 tests passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
