const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const code=fs.readFileSync(__dirname+'/souju.js','utf8');let passed=0;
function context(handler){const stored={};return vm.createContext({Widget:{storage:{get:async k=>stored[k],set:async(k,v)=>stored[k]=v},http:{get:(u,o)=>handler(u,null,o),post:(u,b,o)=>handler(u,b,o)}}});}
function ctx(handler){const c=context(handler);vm.runInContext(code,c);return c;}
function ok(data,headers={}){return {statusCode:200,data,headers};}
function guest(){return {statusCode:201,data:{expires_at:new Date(Date.now()+3600000).toISOString()},headers:{'Set-Cookie':'ai_movie_session=; Path=/v1; Max-Age=0, ai_movie_session=; Path=/; Max-Age=0, ai_movie_session=test; Path=/; Secure; HttpOnly'}};}
const card={id:'av_movie',title:'测试电影',content_kind:'movie',year:2026,poster_url:'https://images.test.org/a.jpg',genres:['科幻']};
const episode={id:'av_ep',token:'av_token',title:'第01集'};
const page=(eps=[episode],more=false)=>({variant_id:'av_movie',episodes:eps,episode_pagination:{has_more:more}});
async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
(async()=>{
 await test('portable HMAC matches independent Node crypto for Unicode, long keys and block boundaries',()=>{
  const c=ctx(()=>{});for(const key of ['abc','密钥','k'.repeat(100)])for(const text of ['', 'GET\n/v1/search?q=%E4%B8%AD\n123\nnonce','中文','a'.repeat(55),'a'.repeat(64),'a'.repeat(200)])assert.equal(c.sjHmac(key,text),crypto.createHmac('sha256',key).update(text).digest('hex'));
 });
 await test('empty mobile landing search makes no HTTP calls',async()=>{const c=ctx(()=>assert.fail('HTTP'));assert.equal((await c.search({keyword:' \u200b '})).length,0);});
 await test('concurrent requests share one visitor session and preserve exact signature/query',async()=>{
  let count=0;const c=ctx(async(u,b,o)=>{if(b){count++;return guest();}const path=u.replace('https://ai.baipiaozhe.com','');const h=o.headers;assert.equal(h.Cookie,'ai_movie_session=test');assert.equal(h['x-ai-movie-signature'],crypto.createHmac('sha256',c.SOUJU.signingKey).update('GET\n'+path+'\n'+h['x-ai-movie-timestamp']+'\n'+h['x-ai-movie-nonce']).digest('hex'));assert(path.includes('q=%E6%B5%81%E6%B5%AA%E5%9C%B0%E7%90%83'));assert(path.includes('intent=catalog_search'));return ok({cards:[card]});});await Promise.all([c.search({keyword:'流浪地球'}),c.search({keyword:'流浪地球',page:2})]);assert.equal(count,1);
 });
 await test('cookie absence has actionable error and no fake success',async()=>{const c=ctx(()=>ok({}));await assert.rejects(c.loadHome(),/Cookie/);});
 await test('session expiry refreshes once and preserves anonymous visitor identity',async()=>{let guests=0,calls=0,ids=[];const c=ctx((u,b)=>{if(b){guests++;ids.push(b.anonymous_id);return guest();}if(calls++===0)return {statusCode:401,data:{error:{code:'session_expired'}}};return ok({cards:[card]});});assert.equal((await c.search({keyword:'a'})).length,1);assert.equal(guests,2);assert.equal(ids[0],ids[1]);});
 await test('signature failures and throttling do not create visitor retry loops',async()=>{for(const status of [401,429]){let calls=0;const c=ctx((u,b)=>{calls++;return b?guest():{statusCode:status,data:{error:{code:'invalid_request_signature'}}};});await assert.rejects(c.loadHome());assert.equal(calls,2);}});
 await test('home deduplicates cards and omits disabled resources',async()=>{const c=ctx((u,b)=>b?guest():ok({sections:[{cards:[card,card,{...card,id:'av_disabled',availability:{disabled:true}}]}]}));const items=await c.loadHome();assert.equal(items.length,1);assert.equal(items[0].posterPath,card.poster_url);});
 await test('categories and page values validated before requests',async()=>{const c=ctx(()=>assert.fail('HTTP'));await assert.rejects(c.loadCatalog({kind:'unknown'}));await assert.rejects(c.loadCatalog({page:-1}));});
 await test('paginated episodes expose next page without mixing seasons',async()=>{const c=ctx((u,b)=>b?guest():ok(u.includes('/episodes?')?page([episode],true):{...card,variants:[{id:'av_season',title:'第二季',has_playback:true}]}));const d=await c.loadDetail(c.sjLink('av_movie'));assert.equal(d.episodeItems.length,1);assert(d.episodeItems[0].link.endsWith('?offset=0'));assert(d.childItems[0].link.endsWith('?offset=1'));assert.equal(d.childItems[1].title,'第二季');});
 await test('episode identity must belong to selected title; explicit page bounds playback to one request',async()=>{let calls=0;const c=ctx((u,b)=>{if(b)return guest();calls++;return ok(page());});await assert.rejects(c.loadResource({link:c.sjEpisodeLink('av_movie','av_wrong',100)}),/未找到/);assert.equal(calls,1);});
 await test('playback keeps direct visitor media, removes duplicates/tickets/restricted sources and session headers',async()=>{const c=ctx((u,b)=>b?guest():ok(u.includes('/episodes?')?page():{current_episode:episode,line_options:[{label:'高清',url:'https://video.test.org/a.mp4',resolved:true,headers:{Referer:'https://media.test.org/',Cookie:'private',Authorization:'private'}},{url:'https://video.test.org/a.mp4'},{url:'resolve://ticket',resolve_required:true},{url:'https://vip.test.org/a',minimum_user_level:1},{url:'https://parser.test.org/',resolve_mode:'parse'}]}));const sources=await c.loadResource({link:c.sjEpisodeLink('av_movie','av_ep',0)});assert.equal(sources.length,1);assert.equal(sources[0].customHeaders.Referer,'https://media.test.org/');assert(!sources[0].customHeaders.Cookie);});
 await test('mismatched resolved episode and external links are rejected',async()=>{const c=ctx((u,b)=>b?guest():ok(u.includes('/episodes?')?page():{current_episode:{id:'av_other'},line_options:[]}));await assert.rejects(c.loadResource({link:c.sjEpisodeLink('av_movie','av_ep',0)}),/不匹配/);await assert.rejects(c.loadDetail('https://evil.test/player/av_movie'));});
 await test('failed storage still reuses current session and does not read stale persisted state',async()=>{let calls=0;const c=ctx((u,b)=>{if(b){calls++;return guest();}return ok({cards:[card]});});c.Widget.storage={get:async()=>null,set:async()=>{throw Error('unavailable');}};await c.search({keyword:'a'});await c.search({keyword:'b'});assert.equal(calls,1);});
 console.log(passed+' souju tests passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
