const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const code=fs.readFileSync(__dirname+'/kanju.js','utf8');let passed=0;
const episode={id:'av_ep',token:'av_token',title:'第1集'},line={id:'source-s',playback_source_id:'source-s',provider_id:'bytevod-lv3',label:'官方S',url:'resolve://ticket-s',url_kind:'resolve_ticket',resolve_required:true,selected:true,minimum_user_level:0};
function context(){const calls=[],values={},c=vm.createContext({Widget:{storage:{get:async k=>values[k],set:async(k,v)=>values[k]=v},http:{get:async()=>({statusCode:200,data:'#EXTM3U\n#EXTINF:6,\nsegment.ts'})}}});vm.runInContext(code,c);c.sjApi=async(p,b)=>{calls.push({p,b});return c.handler(p,b);};c.handler=p=>p.includes('/quota?')?quota(c):p.includes('/episodes?')?{variant_id:'av_movie',episodes:[episode],episode_pagination:{has_more:false,total_count:1}}:p.includes('/resolve-line?')?result():{current_episode:episode,line_options:[line,{id:'direct',label:'直连',url:'https://media.test/direct.m3u8',resolved:true}]};return {c,calls,values};}
function quota(c,remaining=900000){return {object:'user.daily_token_quota',role:'guest',authenticated:false,usage_date:c.sjAiQuotaDay(),used_tokens:900000-remaining,reserved_tokens:0,limit_tokens:900000,remaining_tokens:remaining,reset_at:new Date(Date.now()+3600000).toISOString()};}
function result(){return {object:'playback.line.resolve',current_episode:episode,line:{id:'source-s',playback_source_id:'source-s',label:'官方S',url:'https://media.test/ai.m3u8',url_kind:'m3u8',resolved:true,resolve_required:false},quota_delta:{used_tokens:90000}};}
async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
(async()=>{
 await test('independent metadata, domain, quota and signature configuration',()=>{const {c}=context();assert.equal(c.WidgetMetadata.id,'joeshu.kanju');assert.equal(c.WidgetMetadata.title,'看剧AI');assert.equal(c.WidgetMetadata.version,'0.1.0');assert.equal(c.SOUJU.site,'https://kanju3.com');assert.equal(c.SjAiDailyLimit,900000);assert.equal(c.SjAiQuotaKey,'kanju.aiQuota.v1');assert(c.WidgetMetadata.modules.find(m=>m.id==='loadResource').params.find(p=>p.name==='aiSource').enumOptions.some(x=>x.value==='bytevod-lv3'));assert(!code.includes('souju.'));assert(!code.includes('ai.baipiaozhe.com'));});
 await test('observed public HMAC signs exact Kanju path and query independently',async()=>{const {c}=context();c.Widget.http.get=async(url,opts)=>{const h=opts.headers,text='GET\n/v1/feed/home?scope=public\n'+h['x-ai-movie-timestamp']+'\n'+h['x-ai-movie-nonce'];assert.equal(h['x-ai-movie-signature'],crypto.createHmac('sha256',c.SOUJU.signingKey).update(text).digest('hex'));assert.equal(h.Origin,'https://kanju3.com');return {statusCode:200,data:{}};};await c.sjRaw('/v1/feed/home?scope=public');});
 await test('201 anonymous session is shared and preserves independent stable visitor',async()=>{const {c,values}=context();let posts=0;c.Widget.http.post=async()=>{posts++;return {statusCode:201,data:{expires_at:new Date(Date.now()+3600000).toISOString()},headers:{'Set-Cookie':'ai_movie_session=kanju-session; Path=/; Secure'}};};await Promise.all([c.sjSession(),c.sjSession()]);assert.equal(posts,1);assert(values['kanju.visitor']);assert(values['kanju.session']);assert(!values['souju.visitor']);});
 await test('empty search is idle and actual browsing arguments preserve filters',async()=>{const {c,calls}=context();assert.equal((await c.search({keyword:'\u200B'})).length,0);assert.equal(calls.length,0);c.handler=()=>({cards:[]});await c.loadCatalog({kind:'movie',genre:'科幻',area:'美国',year:'current',page:2});assert(calls[0].p.includes('kind=movie'));assert(calls[0].p.includes('page=2'));await assert.rejects(c.loadCatalog({kind:'invalid'}),/分类无效/);});
 await test('195 coherent episodes keep offsets and never fabricate planned total',async()=>{const {c}=context();const eps=Array.from({length:195},(_,i)=>({id:'av_ep'+i,token:'av_token'+i,title:'第'+(i+1)+'集'}));c.handler=p=>{if(!p.includes('/episodes?'))return {id:'av_movie',title:'凡人修仙传',content_kind:'anime',remarks:'更新至195集 / 共888集'};const offset=Number(p.match(/offset=(\d+)/)[1]);return {variant_id:'av_movie',episodes:eps.slice(offset,offset+100),episode_pagination:{offset,total_count:195,has_more:offset===0}};};const d=await c.loadDetail(c.sjLink('av_movie'));assert.equal(d.episodeItems.length,195);assert(d.episodeItems[100].link.endsWith('offset=100'));assert.match(d.description,/实际取得 195/);});
 await test('premature terminal page never becomes a successful 100-episode detail',async()=>{const {c}=context();c.handler=p=>p.includes('/episodes?')?{variant_id:'av_movie',episodes:[episode],episode_pagination:{total_count:195,has_more:false}}:{id:'av_movie',title:'test'};await assert.rejects(c.loadDetail(c.sjLink('av_movie')),e=>e.code==='EPISODES_INCOMPLETE');});
 await test('real quota displays server balance and refresh alongside local records',async()=>{const {c,calls,values}=context();values[c.SjAiQuotaKey]=JSON.stringify({version:1,day:c.sjAiQuotaDay(),usedTokens:10000,reservedTokens:100000,blocked:false});c.handler=()=>({...quota(c,800000),user_id:'must-not-be-exposed'});const [i]=await c.loadAiQuotaStatus();assert.match(i.description,/原站剩余 800,000 \/ 900,000/);assert.match(i.description,/原站下次刷新/);assert.match(i.description,/本组件已记录用量 10,000/);assert(!i.description.includes('must-not-be-exposed'));assert.equal(calls.length,1);});
 await test('quota outage retains explicit local-only status, invalid quota blocks parse',async()=>{const {c,calls}=context();c.handler=()=>({object:'bad'});assert.match((await c.loadAiQuotaStatus())[0].description,/原站额度暂无法读取/);calls.length=0;await assert.rejects(c.sjAiResource({line_options:[line]},episode,'recommended'),/额度格式异常/);assert.equal(calls.filter(x=>x.p.includes('resolve-line')).length,0);});
 await test('server remaining and local guard both stop before paid parsing',async()=>{for(const mode of ['origin','local']){const {c,calls,values}=context();if(mode==='origin'){const handler=c.handler;c.handler=p=>p.includes('/quota?')?quota(c,50000):handler(p);}else values[c.SjAiQuotaKey]=JSON.stringify({version:1,day:c.sjAiQuotaDay(),usedTokens:850000,reservedTokens:0,blocked:false});await assert.rejects(c.sjAiResource({line_options:[line]},episode,'recommended'),/余量不足/);assert.equal(calls.filter(x=>x.p.includes('resolve-line')).length,0);}});
 await test('server insufficient quota falls back to exact-episode direct without paid call',async()=>{const {c,calls}=context(),handler=c.handler;c.handler=p=>p.includes('/quota?')?quota(c,50000):handler(p);const r=await c.loadResource({link:c.sjEpisodeLink('av_movie','av_ep',0),lineMode:'aiQuotaFallback'});assert(r[0].name.startsWith('直连'));assert.equal(calls.filter(x=>x.p.includes('resolve-line')).length,0);});
 await test('official S parses exactly one ticket and settles reported cost',async()=>{const {c,calls,values}=context();const r=await c.sjAiResource({line_options:[line]},episode,'bytevod-lv3');assert(r[0].name.includes('官方S'));assert.equal(calls.filter(x=>x.p.includes('resolve-line')).length,1);assert.equal(calls.find(x=>x.p.includes('resolve-line')).b.ticket,'ticket-s');const s=JSON.parse(values[c.SjAiQuotaKey]);assert.equal(s.usedTokens,90000);assert.equal(s.reservedTokens,0);});
 await test('wrong resolved episode is rejected and 429 is never retried',async()=>{for(const failure of ['identity','429']){const {c,calls}=context(),handler=c.handler;c.handler=p=>{if(!p.includes('resolve-line'))return handler(p);if(failure==='429'){const e=Error('limited');e.code='RATE_LIMIT';throw e;}return {...result(),current_episode:{id:'av_other'}};};await assert.rejects(c.sjAiResource({line_options:[line]},episode,'recommended'));assert.equal(calls.filter(x=>x.p.includes('resolve-line')).length,1);}});
 await test('direct mode does not invoke quota or parser and strips account headers',async()=>{const {c,calls}=context(),handler=c.handler;c.handler=p=>p.includes('/resolve/')?{current_episode:episode,line_options:[line,{label:'直连',url:'https://media.test/a.mp4',headers:{Cookie:'secret',Authorization:'secret',Referer:'https://media.test/'},resolved:true}]}:handler(p);const r=await c.loadResource({link:c.sjEpisodeLink('av_movie','av_ep',0),lineMode:'all'});assert.equal(r.length,1);assert.equal(r[0].customHeaders.Cookie,undefined);assert.equal(calls.filter(x=>x.p.includes('quota')||x.p.includes('resolve-line')).length,0);});
 await test('HLS empty bodies, HTML and repeated manifests rejected without downloading segments',async()=>{const {c}=context();for(const body of ['<html>bad</html>','#EXTM3U\n#EXT-X-VERSION:3\nfile.ts']){c.Widget.http.get=async()=>({statusCode:200,data:body});await assert.rejects(c.sjProbeHls({url:'https://media.test/a.m3u8',customHeaders:{}}));}});
 console.log(passed+' Kanju tests passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
