// Public XiaoBao pages. JSON data only; no remote JavaScript execution.
var XB_SITE='https://xiaoheimi.cc',XbCategories=[['1','电影'],['2','电视剧'],['4','动漫'],['3','综艺']];
var WidgetMetadata={id:'joeshu.xiaobao',title:'小宝影院',author:'joeshu',site:XB_SITE,version:'0.1.0',requiredVersion:'0.0.1',description:'小宝/小新同站独立模块：首页、四类片库、搜索、完整分集与同集线路检查。',detailCacheDuration:0,modules:[{id:'home',title:'首页推荐与近期条目',functionName:'loadHome',cacheDuration:60,params:[]},{id:'catalog',title:'分类片库',functionName:'loadCatalog',cacheDuration:60,params:[{name:'category',title:'分类',type:'enumeration',value:'2',enumOptions:XbCategories.map(function(x){return {value:x[0],title:x[1]};})},{name:'page',title:'页码',type:'page',value:'1'}]},{id:'searchList',title:'搜索影片',functionName:'search',cacheDuration:0,params:[{name:'keyword',title:'片名',type:'input'},{name:'page',title:'页码',type:'page',value:'1'}]},{id:'loadResource',title:'获取播放线路',type:'stream',functionName:'loadResource',cacheDuration:0,params:[{name:'qualityPreference',title:'画质',type:'enumeration',value:'highest',enumOptions:[{title:'最高可用（自适应）',value:'highest'},{title:'固定高画质',value:'fixed'}]}]}],search:{title:'小宝影院搜索',functionName:'search',params:[{name:'keyword',title:'片名',type:'input'},{name:'page',title:'页码',type:'page',value:'1'}]}};
var xbDetails=Object.create(null),xbStreams=Object.create(null);
function xbText(v){return String(v==null?'':v).replace(/<[^>]*>/g,'').replace(/\s+/g,' ').trim();}
function xbUrl(u){if(typeof u!=='string'||u.length>8192||/[\s\x00-\x1f\\]/.test(u)||!/^https?:\/\/[^/@?#]+(?:[/?#]|$)/i.test(u))throw new Error('小宝资源地址无效');return u;}
function xbPage(v){var n=Number(v==null?1:v);if(!Number.isSafeInteger(n)||n<1||n>1000)throw new Error('页码无效');return n;}
function xbParse(link){var path=String(link).replace(XB_SITE,'');if(XB_SITE+path!==String(link))throw new Error('请选择小宝影院模块中的影片');var m=path.match(/^\/index\.php\/vod\/(?:detail\/id\/(\d{1,10})|play\/id\/(\d{1,10})\/sid\/(\d{1,3})\/nid\/(\d{1,5}))\.html$/);if(!m)throw new Error('小宝影片或分集地址无效');return {id:m[1]||m[2],sid:m[3]||null,nid:m[4]?Number(m[4]):null,path:path};}
function xbHeaders(){return {'User-Agent':'Mozilla/5.0',Referer:XB_SITE+'/'};}
async function xbGet(path){var r=await Widget.http.get(XB_SITE+path,{headers:xbHeaders()}),s=Number(r.statusCode||r.status);if(s===429){var e=new Error('小宝请求过于频繁，请稍后重试');e.code='RATE_LIMIT';throw e;}if(s!==200)throw new Error('小宝入口暂不可用（HTTP '+s+'）');var t=r.data;if(typeof t!=='string'||t.length>4*1024*1024||!/<html|<!doctype/i.test(t))throw new Error('小宝页面格式异常');if(/<title>[^<]*(?:验证|Just a moment)/i.test(t)||/name=["']verify["']/i.test(t))throw new Error('小宝原站要求验证，请在原站正常完成；App未必共享浏览器会话');return t;}
function xbCover(v){v=v||'';if(v.slice(0,2)==='//')v='https:'+v;else if(v[0]==='/')v=XB_SITE+v;return v?xbUrl(v):'';}
async function xbCards(html,category){var $=await Widget.html.load(html),items=[],seen=Object.create(null);$('a.myui-vodlist__thumb[href]').each(function(i,el){var a=$(el),path=a.attr('href'),ids;try{ids=xbParse(XB_SITE+path);}catch(e){return;}if(ids.sid||seen[ids.id])return;var title=xbText(a.attr('title'));if(!title)return;seen[ids.id]=true;var cover=xbCover(a.attr('data-original')||a.find('img').attr('data-original')||a.find('img').attr('src')),link=XB_SITE+path,item={id:link,type:'url',link:link,title:title,coverUrl:cover,posterPath:cover,releaseDate:xbText(a.find('.pic-tag-top .tag').first().text()),description:xbText(a.find('.pic-text').text())};if(category)item.mediaType=String(category)==='1'?'movie':'tv';items.push(item);});return items;}
async function loadHome(){return xbCards(await xbGet('/'));}
async function loadCatalog(p){p=p||{};var c=String(p.category||'2'),page=xbPage(p.page);if(!XbCategories.some(function(x){return x[0]===c;}))throw new Error('分类无效');return xbCards(await xbGet('/index.php/vod/type/id/'+c+(page===1?'':'/page/'+page)+'.html'),c);}
async function search(p){p=p||{};var q=xbText(p.keyword),page=xbPage(p.page);if(!q)return [];if(q.length>60)throw new Error('关键词最多60字');return xbCards(await xbGet('/index.php/vod/search'+(page===1?'':('/page/'+page))+'.html?wd='+encodeURIComponent(q)));}
async function xbDecode(html,ids){var $=await Widget.html.load(html),box=$('.myui-content__detail').first(),title=xbText(box.find('h1.title').text());if(!title||String(box.find('#rating').attr('data-id'))!==ids.id)throw new Error('小宝详情与所选影片不匹配');var lines=[],seen=Object.create(null);$('.tab-pane[id^="playlist"]').each(function(i,el){var tab=$(el),list=[],sid=null,name=xbText($('a[href="#'+tab.attr('id')+'"]').first().text());tab.find('.myui-content__list a[href]').each(function(j,e){var a=$(e),ep=xbParse(XB_SITE+a.attr('href'));if(ep.id!==ids.id||ep.nid===null||ep.nid<1)throw new Error('小宝线路分集与影片不匹配');if(sid!==null&&sid!==ep.sid)throw new Error('小宝线路混杂');sid=ep.sid;if(seen[ep.path])throw new Error('小宝分集地址重复');seen[ep.path]=true;list.push({path:ep.path,nid:ep.nid,title:xbText(a.text())});});if(list.length){list.sort(function(a,b){return a.nid-b.nid;});list.forEach(function(e,i){if(e.nid!==i+1)throw new Error('小宝分集列表不完整');});if(list.length>10000)throw new Error('小宝分集数量异常');lines.push({sid:sid,name:name||'线路 '+sid,episodes:list});}});if(!lines.length||lines.length>20)throw new Error('小宝没有可用分集');var status=xbText(box.find('.text-red').first().text()),count=status.match(/(?:更新至第?|全)\s*(\d+)\s*集/);if(count&&Math.max.apply(null,lines.map(function(l){return l.episodes.length;}))<Number(count[1]))throw new Error('小宝已更新集数与分集列表不完整');var cover=xbCover($('.myui-content__thumb img').first().attr('data-original')||$('.myui-content__thumb img').first().attr('src')),link=XB_SITE+'/index.php/vod/detail/id/'+ids.id+'.html',year=box.find('a[href*="/year/"]').first().text(),genre=xbText(box.find('a[href*="/vod/show/id/"]').first().text()),item={id:link,type:'url',link:link,title:title,coverUrl:cover,posterPath:cover,releaseDate:xbText(year),genreTitle:genre,description:[status,xbText($('#desc .content').first().text())].filter(Boolean).join('\n')};if(/剧|动漫|综艺/.test(genre))item.mediaType='tv';else if(/片|电影/.test(genre))item.mediaType='movie';return {item:item,lines:lines};}
async function xbDetail(ids){var key=ids.id;if(xbDetails[key])return xbDetails[key];xbDetails[key]=(async function(){return xbDecode(await xbGet('/index.php/vod/detail/id/'+ids.id+'.html'),ids);})();try{return await xbDetails[key];}finally{delete xbDetails[key];}}
async function loadDetail(link){var ids=xbParse(link),d=await xbDetail(ids),line=ids.sid?d.lines.find(function(l){return l.sid===ids.sid;}):d.lines.slice().sort(function(a,b){return b.episodes.length-a.episodes.length;})[0];if(!line)throw new Error('小宝所选线路不存在');var item=d.item;item.episodeItems=line.episodes.map(function(ep){var u=XB_SITE+ep.path;return {id:u,type:'url',link:u,title:ep.title,coverUrl:item.coverUrl,mediaType:item.mediaType,childItems:d.lines.map(function(l){var e=l.episodes.find(function(e){return e.nid===ep.nid&&e.title===ep.title;});if(!e)return null;var url=XB_SITE+e.path;return {id:url,type:'url',link:url,title:l.name+' · '+e.title,coverUrl:item.coverUrl,mediaType:item.mediaType};}).filter(Boolean)};});return item;}
function xbPlayer(html,ep){var m=html.match(/\bvar\s+player_aaaa\s*=\s*(\{[^<]*\})\s*;?\s*<\/script>/);if(!m)throw new Error('小宝播放器数据格式已变化');var d;try{d=JSON.parse(m[1]);}catch(e){throw new Error('小宝播放器不是有效JSON');}if(String(d.id)!==ep.id||String(d.sid)!==ep.sid||Number(d.nid)!==ep.nid)throw new Error('小宝播放数据与分集不匹配');if(Number(d.points)!==0||Number(d.trysee)!==0)throw new Error('小宝资源有付费或试看限制');if(Number(d.encrypt)!==0)throw new Error('小宝线路需要额外解析，请选择其他线路');return xbUrl(d.url);}
async function xbResources(ids,preference){if(!ids.sid)throw new Error('请先选择小宝分集');var d=await xbDetail(ids),selected=d.lines.find(function(l){return l.sid===ids.sid;}),ep=selected&&selected.episodes.find(function(e){return e.nid===ids.nid;});if(!ep)throw new Error('小宝分集不存在');var candidates=[ep];d.lines.forEach(function(l){if(l.sid===selected.sid)return;var e=l.episodes.find(function(e){return e.nid===ep.nid&&e.title===ep.title;});if(e)candidates.push(e);});var out=[],last,seen=Object.create(null),budget={reads:0,maxReads:6};for(var i=0;i<Math.min(3,candidates.length);i++)try{var e=candidates[i],ident=xbParse(XB_SITE+e.path),u=xbPlayer(await xbGet(e.path),ident);if(seen[u])continue;seen[u]=true;var info;if(/\.m3u8(?:[?#]|$)/i.test(u))info=await xbHls(u,xbHeaders(),preference,budget);else if(/\.mp4(?:[?#]|$)/i.test(u))info={url:u};else throw new Error('小宝线路未提供M3U8/MP4直连');var name='线路 '+ident.sid+' · '+ep.title;if(info.height)name+=' · 清单 '+info.width+'×'+info.height;if(info.fixed)name+=' · 固定';if(info.retained&&preference==='fixed')name+=' · 自适应（保留音轨/字幕）';out.push({name:name,url:info.url,playerType:'app',customHeaders:xbHeaders()});}catch(e){if(e.code==='RATE_LIMIT')throw e;last=e;}if(!out.length)throw last||new Error('小宝暂无可用线路');return out;}
async function loadResource(p){p=typeof p==='string'?{link:p}:p||{};var ids=xbParse(p.link),quality=p.qualityPreference||'highest';if(['highest','fixed'].indexOf(quality)<0)throw new Error('画质选项无效');var k=p.link+'|'+quality;if(xbStreams[k])return xbStreams[k];xbStreams[k]=xbResources(ids,quality);try{return await xbStreams[k];}finally{delete xbStreams[k];}}

// Bounded HLS inspection; keep external audio and subtitle groups intact.
function xbRelative(base,ref){if(/^https?:\/\//i.test(ref))return xbUrl(ref);if(/^\/\//.test(ref))return xbUrl(base.split(':')[0]+':'+ref);if(/^[a-z][a-z\d+.-]*:/i.test(ref)||/[\s\\]/.test(ref))throw new Error('播放清单地址无效');var m=base.match(/^(https?:\/\/[^/]+)(\/[^?#]*)?/i);if(!m)throw new Error('播放清单地址无效');if(ref.charAt(0)==='?')return m[1]+(m[2]||'/')+ref;var path=ref.charAt(0)==='/'?ref:(m[2]||'/').replace(/[^/]*$/,'')+ref,parts=[];path.split('/').forEach(function(p){if(p==='..')parts.pop();else if(p!=='.')parts.push(p);});return xbUrl(m[1]+parts.join('/'));}
async function xbHls(url,headers,preference,budget){var seen=Object.create(null),reads=0;
 async function read(u,depth,keep){if(depth>=3||++reads>5||seen[u])throw new Error('播放清单检查达到上限');seen[u]=true;if(budget){if(budget.reads>=budget.maxReads)throw new Error('播放清单检查达到总请求上限');budget.reads++;}var r=await Widget.http.get(u,{headers:headers}),s=Number(r.statusCode||r.status);if(s===429){var e=new Error('播放线路请求过于频繁，请稍后重试');e.code='RATE_LIMIT';throw e;}var text=r.data;if(s!==200||typeof text!=='string'||text.length>1024*1024||!/^\s*#EXTM3U/.test(text))throw new Error('小宝影院所选画质清单不可用，请稍后重试');var lines=text.split(/\r?\n/).map(function(l){return l.trim();});if(!/#EXT-X-STREAM-INF:/.test(text)){if(!/#EXTINF:/.test(text)||!lines.some(function(l){return l&&l[0]!=='#';}))throw new Error('播放清单为空');return {url:u};}
 var external=/(?:[:,])(?:AUDIO|SUBTITLES|VIDEO|CLOSED-CAPTIONS)=(?!NONE(?:,|\r?\n|$))/.test(text),variants=[];
 for(var i=0;i<lines.length;i++)if(/^#EXT-X-STREAM-INF:/.test(lines[i])){var res=lines[i].match(/RESOLUTION=(\d+)x(\d+)/),bw=lines[i].match(/(?:[:,])BANDWIDTH=(\d+)/);for(var j=i+1;j<lines.length;j++){if(/^#EXT-X-STREAM-INF:/.test(lines[j]))break;if(lines[j]&&lines[j][0]!=='#'){variants.push({url:xbRelative(u,lines[j]),width:res?Number(res[1]):0,height:res?Number(res[2]):0,bw:bw?Number(bw[1]):0});break;}}}
 variants.sort(function(a,b){return b.width*b.height-a.width*a.height||b.bw-a.bw;});var last;
 for(var v=0;v<Math.min(variants.length,2);v++)try{var chosen=variants[v],child=await read(chosen.url,depth+1,keep||external),fixed=preference==='fixed'&&!keep&&!external&&!child.retained;
 if(v===0&&child.url===chosen.url){return {url:fixed?child.url:u,width:chosen.width,height:chosen.height,fixed:fixed,retained:external||keep||child.retained};}
 if(keep||external)throw new Error('备用清单有独立音轨或字幕，请选择其他来源');return {url:child.url,width:chosen.width,height:chosen.height,fixed:fixed,retained:child.retained};}catch(e){if(e.code==='RATE_LIMIT')throw e;last=e;}
 throw last||new Error('播放子清单不可用');
 }return read(url,0,false);
}
